import { useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { BookOpen, Camera, Download, Trash2 } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { createFieldDiaryEntry, deleteFieldDiaryEntry, listFieldDiaryEntries } from "../services/fieldDiaryStorage";
import type { FieldDiaryActivity, FieldDiaryDraft } from "../types/fieldDiary";
import { diaryActivityLabels, downloadFieldDiaryCsv, sortFieldDiary, summarizeFieldDiary } from "../utils/fieldDiary";

const today = new Date().toISOString().slice(0, 10);
const emptyDraft: FieldDiaryDraft = { farm: "", field: "", crop: "", date: today, activity: "inspection", title: "", responsible: "", weather: "", notes: "", photoName: "", photoDataUrl: "" };
const inputClass = "mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";

export default function FieldDiaryPage() {
  const [entries, setEntries] = useState(() => listFieldDiaryEntries()); const [draft, setDraft] = useState(emptyDraft); const [query, setQuery] = useState(""); const [error, setError] = useState("");
  const summary = summarizeFieldDiary(entries);
  const filtered = useMemo(() => sortFieldDiary(entries.filter((entry) => `${entry.farm} ${entry.field} ${entry.crop} ${entry.title} ${entry.responsible} ${diaryActivityLabels[entry.activity]}`.toLowerCase().includes(query.toLowerCase()))), [entries, query]);

  function selectPhoto(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) { setDraft({ ...draft, photoName: "", photoDataUrl: "" }); return; } if (!file.type.startsWith("image/")) { setError("Selecione um ficheiro de imagem."); event.target.value = ""; return; } if (file.size > 1024 * 1024) { setError("A fotografia deve ter no máximo 1 MB."); event.target.value = ""; return; } const reader = new FileReader(); reader.onload = () => { setDraft((current) => ({ ...current, photoName: file.name, photoDataUrl: String(reader.result ?? "") })); setError(""); }; reader.readAsDataURL(file); }
  function submit(event: FormEvent) { event.preventDefault(); if (!draft.farm.trim() || !draft.field.trim() || !draft.date || !draft.title.trim() || !draft.responsible.trim()) { setError("Preencha exploração, talhão, data, título e responsável."); return; } const created = createFieldDiaryEntry(draft); setEntries((current) => [created, ...current]); setDraft(emptyDraft); setError(""); }
  function remove(id: string) { if (window.confirm("Apagar este registo do diário?")) setEntries(deleteFieldDiaryEntry(id)); }

  return <div className="mx-auto max-w-[1450px] space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 63 · Histórico de campo</p><h1 className="mt-1 text-3xl font-black">Diário do talhão</h1><p className="mt-2 text-sm text-slate-600">Registos e fotografias introduzidos pelo utilizador, guardados localmente neste navegador.</p></div><Button variant="secondary" onClick={() => downloadFieldDiaryCsv(filtered, new Date().toISOString())}><Download size={18}/> Exportar diário CSV</Button></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Registos</p><p className="mt-2 text-3xl font-black">{summary.entries}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Talhões acompanhados</p><p className="mt-2 text-3xl font-black">{summary.fields}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Fotografias</p><p className="mt-2 text-3xl font-black">{summary.photos}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Última atividade</p><p className="mt-2 text-xl font-black">{summary.latestDate ? new Date(`${summary.latestDate}T12:00:00`).toLocaleDateString("pt-PT") : "Sem registos"}</p></Card></section>
    <Card className="p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-black"><BookOpen className="text-emerald-700"/> Novo registo</h2><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm font-semibold">Exploração *<input className={inputClass} value={draft.farm} onChange={(e) => setDraft({ ...draft, farm: e.target.value })}/></label><label className="text-sm font-semibold">Talhão *<input className={inputClass} value={draft.field} onChange={(e) => setDraft({ ...draft, field: e.target.value })}/></label><label className="text-sm font-semibold">Cultura<input className={inputClass} value={draft.crop} onChange={(e) => setDraft({ ...draft, crop: e.target.value })}/></label><label className="text-sm font-semibold">Data *<input type="date" className={inputClass} value={draft.date} onChange={(e) => setDraft({ ...draft, date: e.target.value })}/></label>
      <label className="text-sm font-semibold">Atividade<select className={inputClass} value={draft.activity} onChange={(e) => setDraft({ ...draft, activity: e.target.value as FieldDiaryActivity })}>{Object.entries(diaryActivityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold sm:col-span-2">Título *<input className={inputClass} value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })}/></label><label className="text-sm font-semibold">Responsável *<input className={inputClass} value={draft.responsible} onChange={(e) => setDraft({ ...draft, responsible: e.target.value })}/></label>
      <label className="text-sm font-semibold">Condições observadas<input className={inputClass} placeholder="Ex.: seco, chuva, vento…" value={draft.weather} onChange={(e) => setDraft({ ...draft, weather: e.target.value })}/></label><label className="text-sm font-semibold lg:col-span-2">Observações<input className={inputClass} value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })}/></label><label className="text-sm font-semibold">Fotografia opcional (máx. 1 MB)<input type="file" accept="image/*" className="mt-1.5 block w-full text-sm" onChange={selectPhoto}/><span className="mt-1 block truncate text-xs text-slate-500">{draft.photoName || "Nenhuma fotografia"}</span></label>
      {error && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 sm:col-span-2 lg:col-span-4">{error}</p>}<div className="sm:col-span-2 lg:col-span-4"><Button type="submit"><BookOpen size={18}/> Guardar registo</Button></div>
    </form></Card>
    <Card className="overflow-hidden"><div className="border-b border-slate-200 p-5"><input className="h-11 w-full max-w-lg rounded-xl border border-slate-200 px-3" placeholder="Pesquisar exploração, talhão, atividade ou responsável…" value={query} onChange={(e) => setQuery(e.target.value)}/></div>{filtered.length === 0 ? <p className="p-10 text-center text-slate-500">Nenhum registo encontrado.</p> : <div className="divide-y divide-slate-100">{filtered.map((entry) => <article key={entry.id} className="grid gap-4 p-5 md:grid-cols-[140px_1fr_auto]"><div>{entry.photoDataUrl ? <img src={entry.photoDataUrl} alt={`Fotografia de ${entry.title}`} className="h-28 w-full rounded-xl object-cover"/> : <div className="grid h-28 place-items-center rounded-xl bg-slate-100 text-slate-400"><Camera/></div>}</div><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">{diaryActivityLabels[entry.activity]}</span><span className="text-sm text-slate-500">{new Date(`${entry.date}T12:00:00`).toLocaleDateString("pt-PT")}</span></div><h3 className="mt-2 text-lg font-black">{entry.title}</h3><p className="text-sm font-semibold text-slate-700">{entry.farm} · {entry.field} · {entry.crop || "Cultura não definida"}</p><p className="mt-2 text-sm text-slate-600">{entry.notes || "Sem observações adicionais."}</p><p className="mt-2 text-xs text-slate-500">Responsável: {entry.responsible}{entry.weather ? ` · Condições: ${entry.weather}` : ""}</p></div><button onClick={() => remove(entry.id)} aria-label={`Apagar ${entry.title}`} className="h-fit rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={18}/></button></article>)}</div>}</Card>
  </div>;
}
