import { useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, DatabaseBackup, Download, ShieldCheck, Upload } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { buildProductionChecks, createLocalBackup, downloadLocalBackup, parseLocalBackup, restoreLocalBackup, roleCan, roleLabels, type FarphaRole, type Permission } from "../utils/productionReadiness";

const permissionLabels: Record<Permission, string> = { manage_users: "Gerir utilizadores", manage_farms: "Gerir explorações", edit_operations: "Editar operações", view_reports: "Consultar relatórios", export_data: "Exportar dados", restore_backup: "Restaurar backup" };
export default function ProductionReadinessPage() {
  const [authConfirmed, setAuthConfirmed] = useState(false); const [rlsConfirmed, setRlsConfirmed] = useState(false); const [backupConfirmed, setBackupConfirmed] = useState(false); const [message, setMessage] = useState(""); const fileRef = useRef<HTMLInputElement>(null);
  const storageAvailable = useMemo(() => { try { const key = "farpha.readiness.test"; localStorage.setItem(key, "1"); localStorage.removeItem(key); return true; } catch { return false; } }, []);
  const checks = buildProductionChecks({ supabaseUrl: import.meta.env.VITE_SUPABASE_URL ?? "", anonKey: import.meta.env.VITE_SUPABASE_ANON_KEY ?? "", protocol: window.location.hostname === "localhost" ? "http://localhost" : window.location.protocol, serviceWorker: "serviceWorker" in navigator, storage: storageAvailable, authConfigured: authConfirmed, rlsConfirmed, backupPolicyConfirmed: backupConfirmed }); const blocked = checks.filter((item) => item.status === "blocked").length;
  function exportBackup() { const backup = createLocalBackup(localStorage, new Date().toISOString()); downloadLocalBackup(backup); setMessage(`${Object.keys(backup.entries).length} conjunto(s) de dados locais exportados.`); }
  async function importBackup(file: File) { try { const backup = parseLocalBackup(await file.text()); if (!window.confirm(`Restaurar ${Object.keys(backup.entries).length} conjunto(s) de dados locais? Os valores correspondentes serão substituídos.`)) return; const count = restoreLocalBackup(backup, localStorage); setMessage(`${count} conjunto(s) restaurados. Recarregue a aplicação.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível restaurar o backup."); } }
  return <div className="mx-auto max-w-[1400px] space-y-6"><header><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 70 · Preparação para produção</p><h1 className="mt-1 text-3xl font-black">Segurança, permissões e backups</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Verificação honesta dos requisitos antes de disponibilizar o FARPHA a utilizadores reais.</p></header>
    <section className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Verificações</p><p className="mt-2 text-3xl font-black">{checks.length}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Bloqueios</p><p className="mt-2 text-3xl font-black text-red-700">{blocked}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Estado</p><p className="mt-2 text-xl font-black">{blocked ? "Não liberar ainda" : "Pronto para revisão final"}</p></Card></section>
    <Card className="p-5"><h2 className="flex items-center gap-2 text-xl font-black"><ShieldCheck className="text-emerald-700"/> Checklist de produção</h2><div className="mt-5 grid gap-3 lg:grid-cols-2">{checks.map((check) => <article key={check.id} className={`rounded-xl border p-4 ${check.status === "ready" ? "border-green-200 bg-green-50" : check.status === "warning" ? "border-amber-200 bg-amber-50" : "border-red-200 bg-red-50"}`}><p className="flex items-center gap-2 font-black">{check.status === "ready" ? <CheckCircle2 size={18} className="text-green-700"/> : <AlertTriangle size={18} className={check.status === "blocked" ? "text-red-700" : "text-amber-700"}/>} {check.label}</p><p className="mt-1 text-sm text-slate-600">{check.detail}</p></article>)}</div><div className="mt-5 space-y-2 rounded-xl border border-slate-200 p-4"><p className="text-sm font-black">Confirmações do responsável técnico</p>{[["Autenticação testada com utilizadores reais", authConfirmed, setAuthConfirmed], ["RLS verificada em todas as tabelas", rlsConfirmed, setRlsConfirmed], ["Backup remoto e recuperação testados", backupConfirmed, setBackupConfirmed]].map(([label, value, setter]) => <label key={String(label)} className="flex gap-3 text-sm"><input type="checkbox" checked={Boolean(value)} onChange={(event) => (setter as (value: boolean) => void)(event.target.checked)}/>{String(label)}</label>)}<p className="text-xs text-slate-500">Estas confirmações são apenas o registo desta sessão e não substituem provas técnicas.</p></div></Card>
    <Card className="p-5"><h2 className="flex items-center gap-2 text-xl font-black"><DatabaseBackup className="text-emerald-700"/> Backup dos dados locais</h2><p className="mt-2 text-sm text-slate-600">Inclui apenas chaves `farpha.*` deste navegador. Dados do Supabase não estão incluídos.</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={exportBackup}><Download size={18}/> Exportar backup local</Button><Button variant="secondary" onClick={() => fileRef.current?.click()}><Upload size={18}/> Restaurar backup local</Button><input ref={fileRef} type="file" accept="application/json,.json" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importBackup(file); event.target.value = ""; }}/></div>{message && <p className="mt-4 rounded-xl bg-slate-100 p-3 text-sm font-semibold">{message}</p>}</Card>
    <Card className="overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-black">Matriz de permissões proposta</h2><p className="mt-1 text-sm text-slate-500">Deve ser aplicada no Supabase com autenticação e RLS; não é apenas uma restrição visual.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Perfil</th>{Object.values(permissionLabels).map((label) => <th key={label} className="px-3 py-3 text-center">{label}</th>)}</tr></thead><tbody>{(Object.keys(roleLabels) as FarphaRole[]).map((role) => <tr key={role} className="border-t border-slate-100"><td className="px-5 py-4 font-black">{roleLabels[role]}</td>{(Object.keys(permissionLabels) as Permission[]).map((permission) => <td key={permission} className="px-3 py-4 text-center">{roleCan(role, permission) ? "✓" : "—"}</td>)}</tr>)}</tbody></table></div></Card>
  </div>;
}
