import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Download, FlaskConical, RefreshCw } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { getFarms } from "../../farms/services/farmsService";
import type { Farm } from "../../farms/types/farm";
import { readSoilCache, registerSoilRequest, saveSoilCache } from "../services/soilCache";
import { fetchSoilProfile } from "../services/soilGridsService";
import type { SoilProfile } from "../types/soil";
import { downloadSoilCsv, estimateUncertainty, groupSoilProfile, soilPropertyLabels } from "../utils/soilProfile";

const inputClass = "h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";
export default function SoilIntelligencePage() {
  const [farms, setFarms] = useState<Farm[]>([]); const [farmId, setFarmId] = useState(""); const [latitude, setLatitude] = useState(41.1579); const [longitude, setLongitude] = useState(-8.6291); const [profile, setProfile] = useState<SoilProfile | null>(null); const [fromCache, setFromCache] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; getFarms().then((items) => { if (active) setFarms(items); }).catch(() => undefined); return () => { active = false; }; }, []);
  const farm = farms.find((item) => item.id === farmId); const grouped = useMemo(() => profile ? groupSoilProfile(profile) : [], [profile]);
  function selectFarm(id: string) { setFarmId(id); const selected = farms.find((item) => item.id === id); if (selected) { setLatitude(Number(selected.latitude)); setLongitude(Number(selected.longitude)); setProfile(readSoilCache(Number(selected.latitude), Number(selected.longitude))); setFromCache(Boolean(readSoilCache(Number(selected.latitude), Number(selected.longitude)))); } }
  async function query() { setError(""); const cached = readSoilCache(latitude, longitude); if (cached) { setProfile(cached); setFromCache(true); return; } setLoading(true); try { registerSoilRequest(); const result = await fetchSoilProfile(latitude, longitude); saveSoilCache(result); setProfile(result); setFromCache(false); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível consultar o perfil de solo."); } finally { setLoading(false); } }
  return <div className="mx-auto max-w-[1400px] space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 71 · Estimativa por coordenadas</p><h1 className="mt-1 text-3xl font-black">Solo Inteligente</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Propriedades globais estimadas pelo SoilGrids em resolução de 250 metros e três profundidades.</p></div>{profile && <Button variant="secondary" onClick={() => downloadSoilCsv(profile)}><Download size={18}/> Exportar perfil CSV</Button>}</header>
    <Card className="border-amber-200 bg-amber-50 p-5"><p className="flex items-start gap-3 text-sm text-amber-950"><AlertTriangle className="shrink-0"/><span><b>Serviço beta atualmente instável.</b> O ISRIC informa que a API REST pode estar pausada. O FARPHA usa cache por 30 dias e nunca transforma estas estimativas em análise laboratorial.</span></p></Card>
    <Card className="p-5"><div className="grid gap-4 md:grid-cols-4"><label className="grid gap-1 text-sm font-semibold">Exploração<select className={inputClass} value={farmId} onChange={(event) => selectFarm(event.target.value)}><option value="">Coordenadas manuais</option>{farms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Latitude<input type="number" step="0.0001" className={inputClass} disabled={Boolean(farmId)} value={latitude} onChange={(event) => { setLatitude(Number(event.target.value)); setProfile(null); }}/></label><label className="grid gap-1 text-sm font-semibold">Longitude<input type="number" step="0.0001" className={inputClass} disabled={Boolean(farmId)} value={longitude} onChange={(event) => { setLongitude(Number(event.target.value)); setProfile(null); }}/></label><div className="flex items-end"><Button className="w-full" onClick={() => void query()} disabled={loading}>{loading ? <RefreshCw size={18} className="animate-spin"/> : <FlaskConical size={18}/>} {loading ? "A consultar…" : "Consultar solo"}</Button></div></div><p className="mt-4 text-xs text-slate-500">Ponto: {farm?.name ?? `${latitude.toFixed(4)}, ${longitude.toFixed(4)}`}. O cache evita consultas repetidas e respeita o limite de cinco chamadas por minuto.</p>{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-800">{error} Tente mais tarde ou use dados laboratoriais registados no perfil ambiental.</p>}</Card>
    {!profile ? <Card className="grid min-h-64 place-items-center p-8 text-center"><div><FlaskConical className="mx-auto text-slate-300" size={52}/><h2 className="mt-3 text-xl font-black">Nenhum perfil estimado carregado</h2><p className="mt-2 text-sm text-slate-500">Escolha uma exploração ou coordenadas e consulte o serviço.</p></div></Card> : <><section className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Propriedades</p><p className="mt-2 text-3xl font-black">{new Set(profile.estimates.map((item) => item.property)).size}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Profundidades</p><p className="mt-2 text-3xl font-black">{grouped.filter((item) => item.estimates.length).length}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Origem</p><p className="mt-2 text-xl font-black">{fromCache ? "Cache local" : profile.source}</p><p className="text-xs text-slate-500">{new Date(profile.queriedAt).toLocaleString("pt-PT")}</p></Card></section>
      {grouped.map((group) => group.estimates.length > 0 && <Card key={group.depth} className="overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-black">Profundidade {group.depth}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Propriedade", "Média estimada", "Intervalo Q0.05–Q0.95", "Amplitude relativa"].map((label) => <th key={label} className="px-5 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{group.estimates.map((item) => <tr key={`${item.property}-${item.depth}`}><td className="px-5 py-4 font-black">{soilPropertyLabels[item.property]}</td><td className="px-5 py-4">{item.mean ?? "Sem dados"} {item.unit}</td><td className="px-5 py-4">{item.low ?? "?"} – {item.high ?? "?"} {item.unit}</td><td className="px-5 py-4">{estimateUncertainty(item) ?? "Sem dados"}%</td></tr>)}</tbody></table></div></Card>)}
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Fonte: SoilGrids/ISRIC, licença CC BY 4.0. Resolução aproximada de 250 m. Confirme decisões agronómicas com amostragem e análise laboratorial.</p></>}
  </div>;
}
