import { useEffect, useRef, useState } from "react";
import maplibregl, { type Map as MapLibreMap } from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import { Layers3, MapPinned, RefreshCw } from "lucide-react";
import Card from "../../../design-system/components/Card";
import { getFarms } from "../../farms/services/farmsService";
import type { Farm } from "../../farms/types/farm";
import { buildIcnfWmsUrl, icnfLayers, imageCoordinates, type IcnfLayerId } from "../utils/icnfWms";

export default function IcnfCartographyPage() {
  const containerRef = useRef<HTMLDivElement>(null); const mapRef = useRef<MapLibreMap | null>(null); const activeRef = useRef<Set<IcnfLayerId>>(new Set(["hazard"])); const refreshRef = useRef<() => void>(() => undefined); const [active, setActive] = useState<Set<IcnfLayerId>>(new Set(["hazard"])); const [farms, setFarms] = useState<Farm[]>([]); const [farmId, setFarmId] = useState(""); const [updatedAt, setUpdatedAt] = useState("");
  useEffect(() => { let mounted = true; getFarms().then((items) => { if (mounted) setFarms(items); }).catch(() => undefined); return () => { mounted = false; }; }, []);
  useEffect(() => { if (!containerRef.current || mapRef.current) return; const map = new maplibregl.Map({ container: containerRef.current, center: [-8.1, 39.6], zoom: 6.2, style: { version: 8, sources: { osm: { type: "raster", tiles: ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"], tileSize: 256, attribution: "© OpenStreetMap contributors" } }, layers: [{ id: "osm", type: "raster", source: "osm" }] } }); map.addControl(new maplibregl.NavigationControl(), "top-right");
    const refresh = () => { if (!map.loaded()) return; const bounds = map.getBounds(); const wmsBounds = { west: bounds.getWest(), south: bounds.getSouth(), east: bounds.getEast(), north: bounds.getNorth() }; icnfLayers.forEach((item) => { const sourceId = `icnf-source-${item.id}`; const layerId = `icnf-layer-${item.id}`; if (map.getLayer(layerId)) map.removeLayer(layerId); if (map.getSource(sourceId)) map.removeSource(sourceId); if (!activeRef.current.has(item.id)) return; map.addSource(sourceId, { type: "image", url: buildIcnfWmsUrl(item, wmsBounds), coordinates: imageCoordinates(wmsBounds) }); map.addLayer({ id: layerId, type: "raster", source: sourceId, paint: { "raster-opacity": 0.72, "raster-fade-duration": 0 } }); }); setUpdatedAt(new Date().toISOString()); };
    refreshRef.current = refresh; map.on("load", refresh); map.on("moveend", refresh); mapRef.current = map; return () => { map.remove(); mapRef.current = null; };
  }, []);
  useEffect(() => { activeRef.current = active; refreshRef.current(); }, [active]);
  function toggle(id: IcnfLayerId) { setActive((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  function selectFarm(id: string) { setFarmId(id); const farm = farms.find((item) => item.id === id); if (farm) mapRef.current?.flyTo({ center: [Number(farm.longitude), Number(farm.latitude)], zoom: 12 }); }
  return <div className="mx-auto max-w-[1500px] space-y-6"><header><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-orange-700">Sprint 73 · Dados geográficos oficiais</p><h1 className="mt-1 text-3xl font-black">Cartografia de incêndio ICNF</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Camadas WMS oficiais ajustadas à área visível do mapa.</p></header>
    <div className="grid gap-5 xl:grid-cols-[330px_1fr]"><aside className="space-y-4"><Card className="p-5"><label className="grid gap-1 text-sm font-semibold">Centrar numa exploração<select className="h-11 rounded-xl border border-slate-200 bg-white px-3" value={farmId} onChange={(event) => selectFarm(event.target.value)}><option value="">Portugal Continental</option>{farms.map((farm) => <option key={farm.id} value={farm.id}>{farm.name}</option>)}</select></label></Card><Card className="p-5"><h2 className="flex items-center gap-2 text-lg font-black"><Layers3/> Camadas ICNF</h2><div className="mt-4 space-y-3">{icnfLayers.map((item) => <label key={item.id} className="flex cursor-pointer gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" checked={active.has(item.id)} onChange={() => toggle(item.id)} className="mt-1 accent-orange-600"/><span><span className="flex items-center gap-2 font-black"><i className="h-3 w-3 rounded-full" style={{ backgroundColor: item.color }}/>{item.label}</span><span className="mt-1 block text-xs text-slate-500">{item.description}</span></span></label>)}</div></Card><Card className="p-5 text-sm text-slate-600"><p className="flex items-center gap-2 font-black text-slate-900"><RefreshCw size={17}/> Atualização visual</p><p className="mt-2">As imagens WMS são pedidas novamente após mover ou ampliar o mapa.</p>{updatedAt && <p className="mt-2 text-xs">Último pedido: {new Date(updatedAt).toLocaleTimeString("pt-PT")}</p>}</Card></aside>
      <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-200 p-4"><p className="flex items-center gap-2 font-black"><MapPinned className="text-orange-600"/> Portugal Continental</p><p className="text-xs text-slate-500">Base © OpenStreetMap · Camadas © ICNF</p></div><div ref={containerRef} className="h-[680px] w-full bg-slate-100"/></Card></div>
    <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">A cartografia é informativa e depende da disponibilidade dos serviços ICNF. Consulte metadados, datas e autoridades competentes antes de decisões operacionais.</p>
  </div>;
}
