import { useMemo, useState, type FormEvent } from "react";
import { AlertTriangle, Download, ShieldCheck, Sprout, Trash2 } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { createHarvestRecord, deleteHarvestRecord, listHarvestRecords } from "../services/harvestStorage";
import type { HarvestDraft, HarvestQuality, HarvestQuantityUnit } from "../types/harvest";
import { assessHarvestSafety, calculateHarvestMetrics, downloadHarvestCsv, harvestQualityLabels, summarizeHarvest, summarizeHarvestSafety } from "../utils/harvest";

const today = new Date().toISOString().slice(0, 10); const campaign = String(new Date().getFullYear());
const emptyDraft: HarvestDraft = { campaign, farm: "", field: "", crop: "", harvestDate: today, harvestedAreaHa: 1, grossQuantity: 0, marketableQuantity: 0, unit: "kg", quality: "unclassified", destination: "", notes: "",lotCode:"",hygieneChecked:false,containersClean:false,contaminationIncident:false,incidentNotes:"",safetyStatus:"pending",releasedBy:"",safetyEvidenceReference:"" };
const inputClass = "mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";

export default function HarvestPage() {
  const [records, setRecords] = useState(() => listHarvestRecords()); const [draft, setDraft] = useState(emptyDraft); const [query, setQuery] = useState(""); const [error, setError] = useState("");
  const summary = summarizeHarvest(records); const safetySummary=summarizeHarvestSafety(records); const draftMetrics = calculateHarvestMetrics({ ...draft, id: "preview", createdAt: "" });
  const filtered = useMemo(() => records.filter((record) => `${record.campaign} ${record.farm} ${record.field} ${record.crop} ${record.destination}`.toLowerCase().includes(query.toLowerCase())), [records, query]);
  function submit(event: FormEvent) { event.preventDefault(); if (!draft.campaign.trim() || !draft.farm.trim() || !draft.field.trim() || !draft.crop.trim() || !draft.harvestDate || draft.harvestedAreaHa <= 0 || draft.grossQuantity <= 0 || draft.marketableQuantity < 0 || draft.marketableQuantity > draft.grossQuantity) { setError("Preencha os campos obrigatórios e confirme que a produção comercializável não supera a produção bruta."); return; } const created = createHarvestRecord(draft); setRecords((current) => [created, ...current]); setDraft(emptyDraft); setError(""); }
  function remove(id: string) { if (window.confirm("Apagar este registo de colheita?")) setRecords(deleteHarvestRecord(id)); }
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 82 · Segurança da produção vegetal</p><h1 className="mt-1 text-3xl font-black">Produção e colheita</h1><p className="mt-2 text-sm text-slate-600">Quantidades, qualidade, lotes, higiene e ocorrências registadas pelo utilizador.</p></div><Button variant="secondary" onClick={() => downloadHarvestCsv(filtered, new Date().toISOString())}><Download size={18}/> Exportar colheitas CSV</Button></header>
    <Card className="border-amber-200 bg-amber-50 p-5"><p className="flex gap-3 text-sm text-amber-950"><AlertTriangle className="shrink-0"/><span>O registo ajuda na prevenção e rastreabilidade, mas não certifica segurança alimentar nem substitui análises, HACCP, autoridades ou procedimentos obrigatórios aplicáveis.</span></p></Card>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Colheitas</p><p className="mt-2 text-3xl font-black">{summary.records}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Produção bruta</p><p className="mt-2 text-3xl font-black">{summary.grossTons} t</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Comercializável</p><p className="mt-2 text-3xl font-black text-green-700">{summary.marketableTons} t</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Perdas</p><p className="mt-2 text-3xl font-black text-red-700">{summary.lossPercent}%</p><p className="text-xs text-slate-500">{summary.lossTons} t</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Produtividade</p><p className="mt-2 text-3xl font-black">{summary.yieldTonsPerHa}</p><p className="text-xs text-slate-500">t/ha</p></Card></section>
    <section className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-sm text-slate-500">Lotes libertados</p><p className="mt-2 text-3xl font-black text-emerald-700">{safetySummary.released}</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Segurança pendente</p><p className="mt-2 text-3xl font-black text-amber-700">{safetySummary.pending}</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Lotes bloqueados/ocorrências</p><p className="mt-2 text-3xl font-black text-red-700">{safetySummary.blocked}</p></Card></section>
    <Card className="p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-black"><Sprout className="text-emerald-700"/> Nova colheita</h2><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm font-semibold">Campanha *<input className={inputClass} value={draft.campaign} onChange={(e) => setDraft({ ...draft, campaign: e.target.value })}/></label><label className="text-sm font-semibold">Data *<input type="date" className={inputClass} value={draft.harvestDate} onChange={(e) => setDraft({ ...draft, harvestDate: e.target.value })}/></label><label className="text-sm font-semibold">Exploração *<input className={inputClass} value={draft.farm} onChange={(e) => setDraft({ ...draft, farm: e.target.value })}/></label><label className="text-sm font-semibold">Talhão *<input className={inputClass} value={draft.field} onChange={(e) => setDraft({ ...draft, field: e.target.value })}/></label>
      <label className="text-sm font-semibold">Cultura *<input className={inputClass} value={draft.crop} onChange={(e) => setDraft({ ...draft, crop: e.target.value })}/></label><label className="text-sm font-semibold">Área colhida (ha) *<input type="number" min="0.01" step="0.01" className={inputClass} value={draft.harvestedAreaHa} onChange={(e) => setDraft({ ...draft, harvestedAreaHa: Number(e.target.value) })}/></label><label className="text-sm font-semibold">Unidade<select className={inputClass} value={draft.unit} onChange={(e) => setDraft({ ...draft, unit: e.target.value as HarvestQuantityUnit })}><option value="kg">Quilogramas</option><option value="t">Toneladas</option></select></label><label className="text-sm font-semibold">Qualidade<select className={inputClass} value={draft.quality} onChange={(e) => setDraft({ ...draft, quality: e.target.value as HarvestQuality })}>{Object.entries(harvestQualityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <label className="text-sm font-semibold">Produção bruta *<input type="number" min="0" step="0.01" className={inputClass} value={draft.grossQuantity} onChange={(e) => setDraft({ ...draft, grossQuantity: Number(e.target.value) })}/></label><label className="text-sm font-semibold">Produção comercializável *<input type="number" min="0" step="0.01" className={inputClass} value={draft.marketableQuantity} onChange={(e) => setDraft({ ...draft, marketableQuantity: Number(e.target.value) })}/></label><label className="text-sm font-semibold">Destino<input className={inputClass} placeholder="Mercado, cooperativa…" value={draft.destination} onChange={(e) => setDraft({ ...draft, destination: e.target.value })}/></label><label className="text-sm font-semibold">Código do lote<input className={inputClass} value={draft.lotCode} onChange={(e)=>setDraft({...draft,lotCode:e.target.value})}/></label>
      <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 lg:col-span-4"><h3 className="flex items-center gap-2 font-black"><ShieldCheck size={18}/> Verificação de segurança do lote</h3><div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={draft.hygieneChecked} onChange={e=>setDraft({...draft,hygieneChecked:e.target.checked})}/> Higiene verificada</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={draft.containersClean} onChange={e=>setDraft({...draft,containersClean:e.target.checked})}/> Recipientes limpos</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={draft.contaminationIncident} onChange={e=>setDraft({...draft,contaminationIncident:e.target.checked,safetyStatus:e.target.checked?"blocked":draft.safetyStatus})}/> Ocorrência/contaminação</label><label className="text-sm font-semibold">Estado<select className={inputClass} value={draft.safetyStatus} onChange={e=>setDraft({...draft,safetyStatus:e.target.value as HarvestDraft["safetyStatus"]})}><option value="pending">Pendente</option><option value="released">Libertado</option><option value="blocked">Bloqueado</option></select></label><label className="text-sm font-semibold lg:col-span-2">Descrição da ocorrência<input className={inputClass} value={draft.incidentNotes} onChange={e=>setDraft({...draft,incidentNotes:e.target.value})}/></label><label className="text-sm font-semibold">Libertado por<input className={inputClass} value={draft.releasedBy} onChange={e=>setDraft({...draft,releasedBy:e.target.value})}/></label><label className="text-sm font-semibold">Evidência/checklist<input className={inputClass} value={draft.safetyEvidenceReference} onChange={e=>setDraft({...draft,safetyEvidenceReference:e.target.value})}/></label></div><p className="mt-3 text-xs text-slate-600">Em falta: {assessHarvestSafety(draft).missing.join(", ")||"nenhum campo de controlo"}.</p></div><label className="text-sm font-semibold lg:col-span-4">Observações<input className={inputClass} value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })}/></label>
      <div className="rounded-xl bg-emerald-50 p-4 text-sm lg:col-span-4"><b>Prévia:</b> perdas {draftMetrics.lossPercent}% · produtividade {draftMetrics.yieldTonsPerHa} t/ha</div>{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 sm:col-span-2 lg:col-span-4">{error}</p>}<div className="sm:col-span-2 lg:col-span-4"><Button type="submit"><Sprout size={18}/> Guardar colheita</Button></div>
    </form></Card>
    <Card className="overflow-hidden"><div className="border-b border-slate-200 p-5"><input className="h-11 w-full max-w-lg rounded-xl border border-slate-200 px-3" placeholder="Pesquisar campanha, exploração, talhão ou cultura…" value={query} onChange={(e) => setQuery(e.target.value)}/></div>{filtered.length === 0 ? <p className="p-10 text-center text-slate-500">Nenhuma colheita registada.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Data / Campanha", "Exploração / Talhão", "Cultura / Lote", "Produção", "Perdas", "Produtividade", "Qualidade", "Segurança", ""].map((label) => <th key={label} className="px-5 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((record) => { const metrics = calculateHarvestMetrics(record),safety=assessHarvestSafety(record); return <tr key={record.id}><td className="px-5 py-4"><b>{new Date(`${record.harvestDate}T12:00:00`).toLocaleDateString("pt-PT")}</b><p className="text-sm text-slate-500">{record.campaign}</p></td><td className="px-5 py-4"><b>{record.farm}</b><p className="text-sm text-slate-500">{record.field}</p></td><td className="px-5 py-4">{record.crop}<p className="text-xs text-slate-500">{record.lotCode||"Lote por indicar"}</p></td><td className="px-5 py-4">{record.grossQuantity} {record.unit}<p className="text-sm text-green-700">{record.marketableQuantity} comercializável</p></td><td className="px-5 py-4 font-bold text-red-700">{metrics.lossPercent}%</td><td className="px-5 py-4 font-black">{metrics.yieldTonsPerHa} t/ha</td><td className="px-5 py-4">{harvestQualityLabels[record.quality]}</td><td className={`px-5 py-4 font-bold ${safety.blocked?"text-red-700":safety.complete?"text-emerald-700":"text-amber-700"}`}>{safety.blocked?"Bloqueado/ocorrência":safety.complete?"Verificado":"Pendente"}</td><td className="px-5 py-4"><button onClick={() => remove(record.id)} aria-label={`Apagar ${record.id}`} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></td></tr>; })}</tbody></table></div>}</Card>
  </div>;
}
