export type AuditStatus="ready"|"attention"|"not_applicable";
export type AuditSnapshot={profileConfigured:boolean;overdueObligations:number;documents:number;expiredDocuments:number;treatments:number;treatmentWarnings:number;waterRequired:boolean;validWaterTitles:number;ifapRequired:boolean;ifapApplications:number;ifapMissingReceipts:number;fiscalPending:number;fiscalOverdue:number;insuranceAttention:number;harvestLots:number;traceableLots:number};
export type AuditItem={id:string;area:string;title:string;status:AuditStatus;detail:string;path:string};
export function buildAuditItems(v:AuditSnapshot):AuditItem[]{return[
{id:"profile",area:"Enquadramento",title:"Perfil da exploração",status:v.profileConfigured?"ready":"attention",detail:v.profileConfigured?"Perfil preenchido.":"Preencha o perfil para personalizar as verificações.",path:"/obrigacoes"},
{id:"obligations",area:"Obrigações",title:"Prazos operacionais",status:v.overdueObligations?"attention":"ready",detail:v.overdueObligations?`${v.overdueObligations} prazo(s) ultrapassado(s).`:"Sem prazos ultrapassados registados.",path:"/obrigacoes"},
{id:"documents",area:"Documentos",title:"Evidências documentais",status:v.documents>0&&!v.expiredDocuments?"ready":"attention",detail:v.documents===0?"Nenhum documento no cofre.":v.expiredDocuments?`${v.expiredDocuments} documento(s) expirado(s).`:`${v.documents} documento(s) sem expiração vencida.`,path:"/documentos-conformidade"},
{id:"treatments",area:"Produção",title:"Tratamentos agrícolas",status:v.treatments>0&&!v.treatmentWarnings?"ready":"attention",detail:v.treatments===0?"Sem tratamentos especializados registados.":v.treatmentWarnings?`${v.treatmentWarnings} tratamento(s) exigem revisão.`:`${v.treatments} tratamento(s) revistos.`,path:"/tratamentos-agricolas"},
{id:"water",area:"Ambiente",title:"Água e títulos",status:!v.waterRequired?"not_applicable":v.validWaterTitles>0?"ready":"attention",detail:!v.waterRequired?"Captação não indicada no perfil.":v.validWaterTitles?"Existe título dentro da validade indicada.":"Confirme e registe o título aplicável.",path:"/agua-ambiente"},
{id:"ifap",area:"Apoios",title:"IFAP e PEPAC",status:!v.ifapRequired?"not_applicable":v.ifapApplications>0&&!v.ifapMissingReceipts?"ready":"attention",detail:!v.ifapRequired?"Apoios não indicados no perfil.":v.ifapApplications===0?"Sem candidatura registada.":v.ifapMissingReceipts?`${v.ifapMissingReceipts} candidatura(s) sem comprovativo.`:"Candidaturas com comprovativo indicado.",path:"/ifap-pepac"},
{id:"fiscal",area:"Gestão",title:"Fiscal, laboral e seguros",status:v.fiscalOverdue||v.insuranceAttention?"attention":v.fiscalPending?"attention":"ready",detail:v.fiscalOverdue?`${v.fiscalOverdue} prazo(s) em atraso.`:v.insuranceAttention?`${v.insuranceAttention} seguro(s) exigem atenção.`:v.fiscalPending?`${v.fiscalPending} assunto(s) por confirmar.`:"Sem pendências registadas.",path:"/fiscal-laboral"},
{id:"traceability",area:"Produto",title:"Rastreabilidade por lote",status:v.harvestLots>0&&v.traceableLots===v.harvestLots?"ready":"attention",detail:v.harvestLots===0?"Sem lotes de colheita.":`${v.traceableLots} de ${v.harvestLots} lote(s) com cadeia completa.`,path:"/rastreabilidade"},
]}
export function summarizeAudit(items:AuditItem[]){const applicable=items.filter(v=>v.status!=="not_applicable"),ready=applicable.filter(v=>v.status==="ready").length;return{areas:items.length,ready,attention:applicable.length-ready,notApplicable:items.length-applicable.length,score:applicable.length?Math.round(ready/applicable.length*100):0}}
