import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Download, Flame, RefreshCw, ShieldAlert } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { getFarms } from "../../farms/services/farmsService";
import type { Farm } from "../../farms/types/farm";
import { readIpmaFireCache, saveIpmaFireCache } from "../services/ipmaFireCache";
import { fetchIpmaFireForecast } from "../services/ipmaFireService";
import type { IpmaFireForecast, IpmaFireLevel } from "../types/ipmaFire";
import { downloadIpmaFireCsv, fireOperationalGuidance, ipmaFireLevelLabels, matchFireForecast } from "../utils/ipmaFire";

const inputClass = "h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-orange-600 focus:ring-4 focus:ring-orange-100";
const levelStyle: Record<IpmaFireLevel, string> = { 1: "border-green-200 bg-green-50 text-green-800", 2: "border-yellow-200 bg-yellow-50 text-yellow-900", 3: "border-orange-200 bg-orange-50 text-orange-900", 4: "border-red-300 bg-red-50 text-red-900", 5: "border-fuchsia-300 bg-fuchsia-50 text-fuchsia-900" };
export default function OfficialFireRiskPage() {
  const [farms, setFarms] = useState<Farm[]>([]); const [farmId, setFarmId] = useState(""); const [latitude, setLatitude] = useState(41.1579); const [longitude, setLongitude] = useState(-8.6291); const [forecast, setForecast] = useState<IpmaFireForecast | null>(() => readIpmaFireCache()); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; getFarms().then((items) => { if (active) setFarms(items); }).catch(() => undefined); return () => { active = false; }; }, []);
  const farm = farms.find((item) => item.id === farmId); const matched = useMemo(() => forecast ? matchFireForecast(forecast, latitude, longitude) : [], [forecast, latitude, longitude]); const maximum = matched.reduce<IpmaFireLevel>((value, item) => Math.max(value, item.level) as IpmaFireLevel, 1);
  function selectFarm(id: string) { setFarmId(id); const selected = farms.find((item) => item.id === id); if (selected) { setLatitude(Number(selected.latitude)); setLongitude(Number(selected.longitude)); } }
  async function refresh() { setLoading(true); setError(""); try { const result = await fetchIpmaFireForecast(); saveIpmaFireCache(result); setForecast(result); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível consultar o IPMA."); } finally { setLoading(false); } }
  const locationLabel = farm?.name ?? `Localização ${latitude.toFixed(4)}, ${longitude.toFixed(4)}`;
  return <div className="mx-auto max-w-[1400px] space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-orange-700">Sprint 72 · Fonte oficial portuguesa</p><h1 className="mt-1 text-3xl font-black">Risco oficial de incêndio</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Previsão municipal do IPMA para hoje, amanhã e depois de amanhã.</p></div>{forecast && matched.length > 0 && <Button variant="secondary" onClick={() => downloadIpmaFireCsv(matched, locationLabel, forecast.fetchedAt)}><Download size={18}/> Exportar risco IPMA CSV</Button>}</header>
    <Card className="p-5"><div className="grid gap-4 md:grid-cols-4"><label className="grid gap-1 text-sm font-semibold">Exploração<select className={inputClass} value={farmId} onChange={(event) => selectFarm(event.target.value)}><option value="">Coordenadas manuais</option>{farms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Latitude<input type="number" step="0.0001" className={inputClass} disabled={Boolean(farmId)} value={latitude} onChange={(event) => setLatitude(Number(event.target.value))}/></label><label className="grid gap-1 text-sm font-semibold">Longitude<input type="number" step="0.0001" className={inputClass} disabled={Boolean(farmId)} value={longitude} onChange={(event) => setLongitude(Number(event.target.value))}/></label><div className="flex items-end"><Button className="w-full" onClick={() => void refresh()} disabled={loading}>{loading ? <RefreshCw size={18} className="animate-spin"/> : <Flame size={18}/>} {loading ? "A consultar…" : "Atualizar IPMA"}</Button></div></div>{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-800">{error} {forecast ? "A última previsão válida continua visível." : "Tente novamente mais tarde."}</p>}<p className="mt-4 text-xs text-slate-500">A associação utiliza o ponto municipal IPMA mais próximo. Confirme o concelho indicado, especialmente junto a fronteiras administrativas.</p></Card>
    {!forecast || !matched.length ? <Card className="grid min-h-64 place-items-center p-8 text-center"><div><Flame className="mx-auto text-slate-300" size={52}/><h2 className="mt-3 text-xl font-black">Consulte a previsão oficial</h2><p className="mt-2 text-sm text-slate-500">É necessária ligação à Internet na primeira consulta.</p></div></Card> : <><section className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Dias oficiais</p><p className="mt-2 text-3xl font-black">{matched.length}</p></Card><Card className={`border p-5 ${levelStyle[maximum]}`}><p className="text-sm font-semibold">Nível máximo</p><p className="mt-2 text-2xl font-black">{ipmaFireLevelLabels[maximum]}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Fonte</p><p className="mt-2 text-2xl font-black">IPMA</p><p className="text-xs text-slate-500">Consulta: {new Date(forecast.fetchedAt).toLocaleString("pt-PT")}</p></Card></section>
      <section className="grid gap-4 lg:grid-cols-3">{matched.map((item) => <Card key={item.date} className={`border p-5 ${levelStyle[item.level]}`}><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wide">{new Date(`${item.date}T12:00:00`).toLocaleDateString("pt-PT", { weekday: "long", day: "2-digit", month: "2-digit" })}</p><h2 className="mt-2 text-2xl font-black">{ipmaFireLevelLabels[item.level]}</h2><p className="mt-1 text-sm font-bold">Nível oficial {item.level}/5</p></div><ShieldAlert size={26}/></div><p className="mt-4 text-sm">{fireOperationalGuidance(item.level)}</p><div className="mt-4 rounded-xl bg-white/60 p-3 text-xs"><p>Código do concelho: <b>{item.municipalityCode}</b></p><p>Distância ao ponto municipal: <b>{item.distanceKm} km</b></p><p>Corrida do modelo: {item.modelRunDate}</p><p>Atualização: {item.fileDate}</p></div></Card>)}</section>
      <Card className="border-red-200 bg-red-50 p-5"><p className="flex items-start gap-3 text-sm text-red-900"><AlertTriangle className="shrink-0"/><span><b>Segurança:</b> consulte as restrições e avisos oficiais antes de utilizar maquinaria, fogo ou realizar trabalhos de risco. Em emergência, ligue 112. O FARPHA não substitui IPMA, ICNF, Proteção Civil ou autoridades locais.</span></p></Card></>}
  </div>;
}
