import type { IpmaFireDay, IpmaFireForecast, IpmaFireLevel, MatchedFireRisk } from "../types/ipmaFire";
export const ipmaFireLevelLabels: Record<IpmaFireLevel, string> = { 1: "Reduzido", 2: "Moderado", 3: "Elevado", 4: "Muito elevado", 5: "Máximo" };
const radians = (degrees: number) => degrees * Math.PI / 180;
export function distanceKm(lat1: number, lon1: number, lat2: number, lon2: number) { const dLat = radians(lat2 - lat1); const dLon = radians(lon2 - lon1); const a = Math.sin(dLat / 2) ** 2 + Math.cos(radians(lat1)) * Math.cos(radians(lat2)) * Math.sin(dLon / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
export function matchNearestMunicipality(day: IpmaFireDay, latitude: number, longitude: number): MatchedFireRisk | null { const nearest = day.municipalities.map((item) => ({ item, distance: distanceKm(latitude, longitude, item.latitude, item.longitude) })).sort((a, b) => a.distance - b.distance)[0]; return nearest ? { date: day.date, municipalityCode: nearest.item.municipalityCode, level: nearest.item.level, distanceKm: Number(nearest.distance.toFixed(2)), modelRunDate: day.modelRunDate, fileDate: day.fileDate } : null; }
export function matchFireForecast(forecast: IpmaFireForecast, latitude: number, longitude: number) { return forecast.days.map((day) => matchNearestMunicipality(day, latitude, longitude)).filter((item): item is MatchedFireRisk => Boolean(item)); }
export function fireOperationalGuidance(level: IpmaFireLevel) { if (level >= 5) return "Risco máximo: consulte imediatamente as restrições oficiais e evite atividades que possam gerar ignição."; if (level >= 4) return "Risco muito elevado: confirme restrições oficiais antes de utilizar maquinaria ou fogo."; if (level >= 3) return "Risco elevado: reforce vigilância, acessos, água disponível e planeamento das operações."; return "Mantenha prevenção e acompanhe as atualizações oficiais."; }
const escapeCsv = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`;
export function buildIpmaFireCsv(items: MatchedFireRisk[], farm: string, fetchedAt: string) { return [["Exploração", "Data", "Código do concelho", "Nível", "Classificação", "Distância ao ponto municipal (km)", "Corrida do modelo", "Atualização do ficheiro", "Consultado em", "Fonte"], ...items.map((item) => [farm, item.date, item.municipalityCode, item.level, ipmaFireLevelLabels[item.level], item.distanceKm, item.modelRunDate, item.fileDate, fetchedAt, "IPMA"])].map((row) => row.map(escapeCsv).join(";")).join("\r\n"); }
export function downloadIpmaFireCsv(items: MatchedFireRisk[], farm: string, fetchedAt: string) { const blob = new Blob([`\uFEFF${buildIpmaFireCsv(items, farm, fetchedAt)}`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "farpha-risco-incendio-ipma.csv"; anchor.click(); URL.revokeObjectURL(url); }
