import { useEffect, useMemo, useState } from "react";
import { Bot, CheckCircle2, Download, ShieldAlert } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { getEnvironmentProfile } from "../../environment/services/environmentService";
import type { FieldEnvironmentProfile } from "../../environment/types/environment";
import { getFarms } from "../../farms/services/farmsService";
import type { Farm } from "../../farms/types/farm";
import { getFieldsByFarm } from "../../fields/services/fieldsService";
import type { Field } from "../../fields/types/field";
import { listFieldDiaryEntries } from "../../field-diary/services/fieldDiaryStorage";
import { listHarvestRecords } from "../../harvest/services/harvestStorage";
import { readWeatherCache } from "../../weather/services/weatherCache";
import { buildRecommendations, downloadRecommendationsCsv } from "../utils/recommendationEngine";

const inputClass = "h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";
const priorityStyle = { urgent: "border-red-300 bg-red-50 text-red-800", high: "border-orange-300 bg-orange-50 text-orange-900", medium: "border-amber-200 bg-amber-50 text-amber-900", low: "border-blue-200 bg-blue-50 text-blue-800" };
const priorityLabel = { urgent: "Urgente", high: "Alta", medium: "Média", low: "Melhoria de dados" };

export default function RecommendationsPage() {
  const [farms, setFarms] = useState<Farm[]>([]); const [fields, setFields] = useState<Field[]>([]); const [farmId, setFarmId] = useState(""); const [fieldId, setFieldId] = useState(""); const [environment, setEnvironment] = useState<FieldEnvironmentProfile | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const diary = useMemo(() => listFieldDiaryEntries(), []); const harvests = useMemo(() => listHarvestRecords(), []); const cachedWeather = useMemo(() => readWeatherCache(), []);
  useEffect(() => { let active = true; getFarms().then((items) => { if (active) setFarms(items); }).catch(() => { if (active) setError("Não foi possível carregar as explorações."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function selectFarm(id: string) { setFarmId(id); setFieldId(""); setEnvironment(null); setFields([]); if (!id) return; try { setFields(await getFieldsByFarm(id)); } catch { setError("Não foi possível carregar os talhões desta exploração."); } }
  async function selectField(id: string) { setFieldId(id); setEnvironment(null); if (!id) return; try { setEnvironment(await getEnvironmentProfile(id)); } catch { setError("O perfil ambiental do talhão não está acessível."); } }
  const farm = farms.find((item) => item.id === farmId); const field = fields.find((item) => item.id === fieldId); const weather = cachedWeather && cachedWeather.farmId === farmId ? cachedWeather.forecast : null;
  const result = useMemo(() => buildRecommendations({ farm: farm?.name ?? "", field: field?.name ?? "", crop: field?.crop || farm?.crop || "", weather, environment, diary, harvests, today: new Date().toISOString() }), [farm, field, weather, environment, diary, harvests]);
  return <div className="mx-auto max-w-[1400px] space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 68 · Apoio à decisão</p><h1 className="mt-1 text-3xl font-black">Recomendações automáticas</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Clima, solo, cultura e histórico reunidos com evidências e nível de confiança.</p></div>{field && <Button onClick={() => downloadRecommendationsCsv(result.recommendations, result.generatedAt)}><Download size={18}/> Exportar recomendações CSV</Button>}</header>
    <Card className="p-5"><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Exploração<select className={inputClass} value={farmId} disabled={loading} onChange={(e) => void selectFarm(e.target.value)}><option value="">Selecione uma exploração</option>{farms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Talhão<select className={inputClass} value={fieldId} disabled={!farmId} onChange={(e) => void selectField(e.target.value)}><option value="">Selecione um talhão</option>{fields.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.crop || "Sem cultura"}</option>)}</select></label></div>{error && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-800">{error}</p>}</Card>
    {!field ? <Card className="grid min-h-64 place-items-center p-8 text-center"><div><Bot className="mx-auto text-slate-300" size={52}/><h2 className="mt-3 text-xl font-black">Selecione uma exploração e um talhão</h2><p className="mt-2 text-sm text-slate-500">O FARPHA não gera recomendações sem identificar o contexto agrícola.</p></div></Card> : <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Confiança dos dados</p><p className="mt-2 text-3xl font-black">{result.confidencePercent}%</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Recomendações</p><p className="mt-2 text-3xl font-black">{result.recommendations.length}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Diário correspondente</p><p className="mt-2 text-3xl font-black">{result.sources.diary}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Colheitas analisadas</p><p className="mt-2 text-3xl font-black">{result.sources.harvests}</p></Card></section>
      <Card className="p-5"><h2 className="text-xl font-black">Fontes utilizadas</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Meteorologia", result.sources.weather, weather ? `${weather.days.length} dias · ${weather.source}` : "Consulte Clima para esta exploração"], ["Perfil ambiental", result.sources.environment, environment ? `Confiança registada: ${environment.data_confidence}%` : "Sem perfil do talhão"], ["Diário", result.sources.diary > 0, `${result.sources.diary} atividade(s)`], ["Colheitas", result.sources.harvests > 0, `${result.sources.harvests} registo(s)`]].map(([label, available, detail]) => <div key={String(label)} className={`rounded-xl border p-4 ${available ? "border-green-200 bg-green-50" : "border-slate-200 bg-slate-50"}`}><p className="flex items-center gap-2 font-black">{available && <CheckCircle2 size={17} className="text-green-700"/>}{String(label)}</p><p className="mt-1 text-xs text-slate-600">{String(detail)}</p></div>)}</div></Card>
      <section className="space-y-3">{result.recommendations.map((item) => <Card key={item.id} className={`border p-5 ${priorityStyle[item.priority]}`}><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-black uppercase tracking-wide">{priorityLabel[item.priority]} · {item.category}</p><h2 className="mt-1 text-xl font-black">{item.title}</h2><p className="mt-2 text-sm">{item.action}</p></div><ShieldAlert className="shrink-0"/></div><div className="mt-4 flex flex-wrap gap-2">{item.evidence.map((evidence) => <span key={evidence} className="rounded-full bg-white/70 px-3 py-1 text-xs font-semibold">{evidence}</span>)}</div></Card>)}</section>
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Recomendações são apoio à decisão, não substituem observação no terreno, análise laboratorial ou aconselhamento agronómico. Nenhuma ação é executada automaticamente.</p>
    </>}
  </div>;
}
