import { describe, expect, it } from "vitest";
import type { RecommendationInput } from "./recommendationEngine";
import { buildRecommendations, buildRecommendationsCsv } from "./recommendationEngine";
const base: RecommendationInput = { farm: "Quinta", field: "Norte", crop: "Vinha", weather: null, environment: null, diary: [], harvests: [], today: "2026-07-20" };
describe("recommendation engine", () => {
  it("gera recomendações climáticas com evidências e prioridade", () => { const result = buildRecommendations({ ...base, weather: { latitude: 41, longitude: -8, timezone: "Europe/Lisbon", generatedAt: "", source: "Open-Meteo", days: [{ date: "2026-07-21", weatherCode: 0, temperatureMax: 41, temperatureMin: -1, precipitationMm: 55, precipitationProbability: 90, windGustKmh: 80, evapotranspirationMm: 5 }] } }); expect(result.recommendations[0].priority).toBe("urgent"); expect(result.recommendations.map((item) => item.id)).toEqual(expect.arrayContaining(["protect-frost", "heat-stress", "rain-operations", "wind-spraying"])); });
  it("cruza solo, drenagem e histórico sem prescrever corretivos", () => { const result = buildRecommendations({ ...base, environment: { id: "e", field_id: "f", farm_id: "a", altitude_m: null, slope_percent: null, exposure: "flat", soil_texture: "clay", soil_ph: 4.9, organic_matter_percent: 1.2, drainage: "poor", water_available: true, irrigation_type: "drip", annual_rainfall_mm: null, average_humidity_percent: null, min_temperature_c: null, max_temperature_c: null, chill_hours: null, frost_risk: "moderate", fire_risk: "moderate", wind_exposure: "low", data_confidence: 70, notes: "" }, harvests: [{ id: "h", campaign: "2025", farm: "Quinta", field: "Norte", crop: "Vinha", harvestDate: "", harvestedAreaHa: 1, grossQuantity: 10, marketableQuantity: 8, unit: "t", quality: "first", destination: "", notes: "", createdAt: "" }] }); expect(result.recommendations.map((item) => item.id)).toEqual(expect.arrayContaining(["soil-ph", "organic-matter", "harvest-loss"])); expect(result.recommendations.find((item) => item.id === "soil-ph")?.action).toContain("análise laboratorial"); });
  it("expõe dados em falta, confiança e exportação transparente", () => { const result = buildRecommendations(base); expect(result.confidencePercent).toBe(0); expect(result.recommendations.map((item) => item.id)).toEqual(["missing-diary", "missing-weather", "missing-soil"]); expect(buildRecommendationsCsv(result.recommendations, result.generatedAt)).toContain('"Sem previsão guardada"'); });
});
