import type { FieldDiaryEntry } from "../../field-diary/types/fieldDiary";
import type { HarvestRecord } from "../../harvest/types/harvest";
import { calculateHarvestMetrics } from "../../harvest/utils/harvest";
import type { FieldEnvironmentProfile } from "../../environment/types/environment";
import type { WeatherForecast } from "../../weather/types/weather";

export type RecommendationPriority = "urgent" | "high" | "medium" | "low";
export type AgriculturalRecommendation = { id: string; priority: RecommendationPriority; category: string; title: string; action: string; evidence: string[] };
export type RecommendationInput = { farm: string; field: string; crop: string; weather: WeatherForecast | null; environment: FieldEnvironmentProfile | null; diary: FieldDiaryEntry[]; harvests: HarvestRecord[]; today: string };

export function buildRecommendations(input: RecommendationInput) {
  const recommendations: AgriculturalRecommendation[] = []; const relevantDiary = input.diary.filter((item) => item.farm.toLowerCase() === input.farm.toLowerCase() && item.field.toLowerCase() === input.field.toLowerCase() && (!input.crop || item.crop.toLowerCase() === input.crop.toLowerCase())); const relevantHarvests = input.harvests.filter((item) => item.farm.toLowerCase() === input.farm.toLowerCase() && item.field.toLowerCase() === input.field.toLowerCase() && (!input.crop || item.crop.toLowerCase() === input.crop.toLowerCase())); const days = input.weather?.days ?? []; const rain = days.reduce((sum, day) => sum + day.precipitationMm, 0); const maxGust = Math.max(0, ...days.map((day) => day.windGustKmh)); const minTemp = Math.min(...(days.length ? days.map((day) => day.temperatureMin) : [Infinity])); const maxTemp = Math.max(...(days.length ? days.map((day) => day.temperatureMax) : [-Infinity]));
  if (minTemp <= 2) recommendations.push({ id: "protect-frost", priority: minTemp <= 0 ? "urgent" : "high", category: "Clima", title: "Preparar proteção contra geada", action: "Confirme a previsão oficial e proteja as culturas sensíveis antes do período frio.", evidence: [`Mínima prevista: ${minTemp} °C`, `Fonte: ${input.weather?.source}`] });
  if (maxTemp >= 35) recommendations.push({ id: "heat-stress", priority: maxTemp >= 40 ? "urgent" : "high", category: "Clima", title: "Reduzir exposição ao calor", action: "Planeie operações para as horas frescas e avalie sinais de stress hídrico no terreno.", evidence: [`Máxima prevista: ${maxTemp} °C`] });
  if (rain >= 20) recommendations.push({ id: "rain-operations", priority: rain >= 50 ? "high" : "medium", category: "Operações", title: "Rever operações antes da chuva", action: "Confirme drenagem, acessos e aplicações planeadas; adie pulverizações quando necessário.", evidence: [`Precipitação acumulada prevista: ${rain.toFixed(1)} mm`] });
  if (maxGust >= 45) recommendations.push({ id: "wind-spraying", priority: maxGust >= 70 ? "high" : "medium", category: "Operações", title: "Evitar pulverizações com vento", action: "Confirme o vento local e reprograme aplicações que possam causar deriva.", evidence: [`Rajada máxima prevista: ${maxGust} km/h`] });
  const env = input.environment; if (env?.soil_ph != null && (env.soil_ph < 5.5 || env.soil_ph > 7.5)) recommendations.push({ id: "soil-ph", priority: "medium", category: "Solo", title: "Confirmar correção do pH", action: "Realize análise laboratorial antes de aplicar corretivos e adapte a decisão à cultura.", evidence: [`pH registado: ${env.soil_ph}`, `Confiança do perfil: ${env.data_confidence}%`] });
  if (env?.organic_matter_percent != null && env.organic_matter_percent < 2) recommendations.push({ id: "organic-matter", priority: "medium", category: "Solo", title: "Melhorar matéria orgânica", action: "Avalie incorporação de matéria orgânica com base em análise de solo e aconselhamento agronómico.", evidence: [`Matéria orgânica registada: ${env.organic_matter_percent}%`] });
  if (env?.drainage === "poor" && rain >= 10) recommendations.push({ id: "drainage", priority: "high", category: "Solo", title: "Vigiar encharcamento", action: "Inspecione as zonas de drenagem e evite a circulação de máquinas em solo saturado.", evidence: ["Drenagem registada: fraca", `Chuva prevista: ${rain.toFixed(1)} mm`] });
  const harvestMetrics = relevantHarvests.map(calculateHarvestMetrics); const averageLoss = harvestMetrics.length ? harvestMetrics.reduce((sum, item) => sum + item.lossPercent, 0) / harvestMetrics.length : 0; if (averageLoss >= 10) recommendations.push({ id: "harvest-loss", priority: "medium", category: "Histórico", title: "Investigar perdas de produção", action: "Compare qualidade, colheita, armazenamento e destino antes da próxima campanha.", evidence: [`Perdas médias registadas: ${averageLoss.toFixed(1)}%`, `${harvestMetrics.length} colheita(s) analisada(s)`] });
  if (!input.weather) recommendations.push({ id: "missing-weather", priority: "low", category: "Dados", title: "Atualizar previsão meteorológica", action: "Abra Clima e consulte a localização da exploração para ativar recomendações meteorológicas.", evidence: ["Sem previsão guardada"] });
  if (!env) recommendations.push({ id: "missing-soil", priority: "low", category: "Dados", title: "Completar perfil ambiental do talhão", action: "Registe textura, pH, matéria orgânica, drenagem e disponibilidade de água.", evidence: ["Sem perfil ambiental acessível"] });
  if (!relevantDiary.length) recommendations.push({ id: "missing-diary", priority: "low", category: "Dados", title: "Atualizar Diário do Talhão", action: "Registe observações e operações para aumentar a qualidade das recomendações.", evidence: ["Sem atividades correspondentes no diário local"] });
  const coverage = [Boolean(input.weather), Boolean(env), relevantDiary.length > 0, relevantHarvests.length > 0].filter(Boolean).length; const confidencePercent = coverage * 25; const order = { urgent: 0, high: 1, medium: 2, low: 3 }; return { recommendations: recommendations.sort((a, b) => order[a.priority] - order[b.priority] || a.title.localeCompare(b.title)), confidencePercent, sources: { weather: Boolean(input.weather), environment: Boolean(env), diary: relevantDiary.length, harvests: relevantHarvests.length }, generatedAt: input.today };
}

const escapeCsv = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`;
export function buildRecommendationsCsv(items: AgriculturalRecommendation[], generatedAt: string) { return [["Prioridade", "Categoria", "Recomendação", "Ação", "Evidências", "Gerado em"], ...items.map((item) => [item.priority, item.category, item.title, item.action, item.evidence.join(" | "), generatedAt])].map((row) => row.map(escapeCsv).join(";")).join("\r\n"); }
export function downloadRecommendationsCsv(items: AgriculturalRecommendation[], generatedAt: string) { const blob = new Blob([`\uFEFF${buildRecommendationsCsv(items, generatedAt)}`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "farpha-recomendacoes.csv"; anchor.click(); URL.revokeObjectURL(url); }
