import { useState, type ReactNode } from "react";
import { ArrowRight, Bot, Check, MapPinned, ShieldCheck, Sparkles } from "lucide-react";
import FarphaLogo from "../../components/brand/FarphaLogo";
import type { UserProfile } from "./AuthContext";

const goalsList=["Organizar explorações e talhões","Planear operações e equipas","Controlar custos e produtividade","Antecipar clima e riscos","Agricultura de precisão","Conformidade e rastreabilidade"];
const steps=[{number:1,label:"Conhecer a operação"},{number:2,label:"Definir prioridades"},{number:3,label:"Começar pelo mapa"}];

export default function FirstRunOnboarding({profile,children}:{profile:UserProfile;children:ReactNode}){
  const key=`farpha.onboarding.${profile.id}`;
  const [complete,setComplete]=useState(()=>localStorage.getItem(key)==="complete");
  const [step,setStep]=useState(1); const [organisation,setOrganisation]=useState(""); const [country,setCountry]=useState("Portugal"); const [goals,setGoals]=useState<string[]>([]);
  if(complete)return <>{children}</>;
  function toggle(goal:string){setGoals(current=>current.includes(goal)?current.filter(item=>item!==goal):[...current,goal])}
  function finish(){localStorage.setItem(key,"complete");localStorage.setItem(`farpha.workspace.${profile.id}`,JSON.stringify({organisation:organisation.trim(),country,goals,createdAt:new Date().toISOString(),empty:true}));setComplete(true)}
  return <main className="min-h-dvh overflow-y-auto bg-[radial-gradient(circle_at_top,#315d3c,#07150d_68%)] p-4 sm:p-8">
    <div className="mx-auto max-w-[1040px]"><header className="flex items-center justify-between"><span className="rounded-xl bg-white px-3 py-2"><FarphaLogo eager className="h-11 w-auto"/></span><p className="text-xs font-black uppercase tracking-[.18em] text-white/45">Configuração inicial · {step}/3</p></header>
      <section className="mt-8 grid overflow-hidden rounded-[32px] bg-white shadow-[0_35px_100px_rgba(0,0,0,.28)] lg:grid-cols-[.72fr_1.28fr]">
        <aside className="bg-[#102d1e] p-7 text-white sm:p-10"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#b8e62e] text-[#102d1e]"><Bot/></span><p className="mt-8 text-xs font-black uppercase tracking-[.18em] text-[#b8e62e]">Inteligência de configuração</p><h1 className="mt-4 text-3xl font-black leading-tight text-white">Vamos preparar o FARPHA para a sua realidade.</h1><p className="mt-4 text-sm leading-7 text-white/55">A configuração orienta os primeiros passos, mas não cria dados agrícolas. A plataforma começa vazia.</p><div className="mt-8 space-y-4">{steps.map(item=><p key={item.label} className={`flex items-center gap-3 text-sm font-bold ${step>=item.number?"text-white":"text-white/30"}`}><span className={`grid h-7 w-7 place-items-center rounded-full text-xs ${step>=item.number?"bg-[#b8e62e] text-[#102d1e]":"bg-white/10"}`}>{step>item.number?<Check size={14}/>:item.number}</span>{item.label}</p>)}</div></aside>
        <div className="p-7 sm:p-10 lg:p-12">
          {step===1&&<><p className="text-xs font-black uppercase tracking-[.18em] text-[#568020]">Bem-vindo, {profile.fullName}</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">Comece com um espaço realmente seu.</h2><p className="mt-4 leading-7 text-[#657168]">Os dados ficam associados à sua conta. Neste momento não existem explorações, talhões, missões ou registos fictícios.</p><div className="mt-7 grid gap-4"><label className="text-sm font-bold">Nome da exploração ou organização<input value={organisation} onChange={event=>setOrganisation(event.target.value)} placeholder="Pode alterar mais tarde" className="mt-2 min-h-12 w-full rounded-xl border border-[#cad5cc] px-4"/></label><label className="text-sm font-bold">País ou região<select value={country} onChange={event=>setCountry(event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-[#cad5cc] bg-white px-4"><option>Portugal</option><option>Espanha</option><option>Brasil</option><option>Angola</option><option>Moçambique</option><option>Outro</option></select></label></div></>}
          {step===2&&<><p className="text-xs font-black uppercase tracking-[.18em] text-[#568020]">Personalizar orientação</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">O que pretende melhorar primeiro?</h2><p className="mt-4 text-[#657168]">Escolha prioridades para personalizar a orientação inicial.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{goalsList.map(goal=><button key={goal} onClick={()=>toggle(goal)} aria-pressed={goals.includes(goal)} className={`min-h-20 rounded-2xl border p-4 text-left text-sm font-black ${goals.includes(goal)?"border-[#5f8e25] bg-[#edf6dd]":"border-[#d8e0d9] hover:border-[#83a65b]"}`}><span className="flex items-start gap-3"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full ${goals.includes(goal)?"bg-[#6f9e24] text-white":"border"}`}>{goals.includes(goal)&&<Check size={13}/>}</span>{goal}</span></button>)}</div></>}
          {step===3&&<><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#edf6dd] text-[#568020]"><MapPinned size={28}/></span><p className="mt-7 text-xs font-black uppercase tracking-[.18em] text-[#568020]">Tudo preparado</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">A primeira decisão começa no mapa.</h2><p className="mt-4 leading-7 text-[#657168]">Crie a primeira exploração e confirme a localização. A Inteligência FARPHA contextualizará clima, riscos e próximos passos a partir dos dados introduzidos.</p><div className="mt-7 rounded-2xl bg-[#f2f6ee] p-5"><p className="flex gap-2 font-black"><Sparkles className="text-[#6f9e24]" size={19}/>O seu espaço está vazio</p><p className="mt-2 text-sm leading-6 text-[#657168]">Nenhuma exploração, talhão, missão, custo ou alerta antigo foi inserido nesta conta.</p></div><p className="mt-5 flex items-start gap-2 text-xs text-[#657168]"><ShieldCheck className="shrink-0 text-[#477627]" size={16}/>As políticas RLS isolam os registos da sua conta.</p></>}
          <div className="mt-9 flex justify-between gap-3">{step>1?<button onClick={()=>setStep(value=>value-1)} className="min-h-12 rounded-xl border border-[#ccd6ce] px-5 font-black">Voltar</button>:<span/>}<button onClick={()=>step<3?setStep(value=>value+1):finish()} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#173c2a] px-6 font-black text-white">{step<3?"Continuar":"Entrar no FARPHA"}<ArrowRight size={18}/></button></div>
        </div>
      </section>
    </div>
  </main>;
}
