import { useState } from "react";
import { Activity, ArrowRight, Bot, Check, ChevronDown, ChevronRight, ClipboardCheck, CloudSun, Coins, FileCheck2, Layers3, Leaf, Map, MapPinned, Menu, PackageCheck, Satellite, ShieldCheck, Sprout, Tractor, TrendingUp, Waves, X, Zap } from "lucide-react";
import FarphaLogo from "../../components/brand/FarphaLogo";

type Props = { onEnter: () => void };
const modules = [
  { icon: MapPinned, title: "Explorações e talhões", text: "Organize propriedades, desenhe limites, consulte áreas e mantenha cada talhão ligado ao seu histórico." },
  { icon: ClipboardCheck, title: "Operações e missões", text: "Planeie tarefas, atribua responsáveis, acompanhe prioridades e transforme alertas em trabalho executável." },
  { icon: CloudSun, title: "Clima e risco", text: "Consulte previsões, disponibilidade hídrica e indicadores de incêndio no contexto de cada exploração." },
  { icon: Satellite, title: "Agricultura de precisão", text: "Reúna observações, indicadores de vegetação, inteligência de solo e contexto espacial para decidir melhor." },
  { icon: Coins, title: "Custos e desempenho", text: "Registe custos agrícolas, acompanhe produtividade e obtenha uma leitura financeira clara da operação." },
  { icon: FileCheck2, title: "Conformidade e auditoria", text: "Centralize documentos, obrigações, tratamentos, rastreabilidade e evidências para preparar verificações." },
  { icon: Tractor, title: "Máquinas e inventário", text: "Controle equipamentos, inspeções, produtos, lotes e movimentos essenciais da exploração." },
  { icon: Bot, title: "Inteligência FARPHA", text: "Receba recomendações explicáveis, prioridades operacionais e ajuda contextual dentro da plataforma." },
];
const mapLayers = ["Explorações e limites", "Talhões e culturas", "Missões e ordens", "Clima e incêndio", "Solo e ambiente", "Satélite e precisão"];
const plans = [
  { name: "Free", price: "€0", text: "Para conhecer o FARPHA e organizar a base da exploração.", items: ["Explorações e talhões", "Mapa operacional", "Recursos essenciais"] },
  { name: "Plus", price: "€19,90", text: "Para operações agrícolas que precisam de controlo e continuidade.", items: ["Tudo do Free", "Operações, custos e alertas", "Relatórios e produtividade"], featured: true },
  { name: "Pro", price: "€49,90", text: "Para utilizar toda a inteligência e conformidade FARPHA.", items: ["Toda a plataforma", "Inteligência e automações", "Auditoria e recursos avançados"] },
];
const faqs = [
  ["O que é o FARPHA?", "É uma plataforma operacional agrícola que centraliza mapa, explorações, talhões, operações, clima, custos, conformidade e inteligência num ambiente único."],
  ["O mapa é apenas uma visualização?", "Não. O mapa funciona como centro de contexto: liga a localização da exploração aos talhões, riscos, missões, observações e decisões operacionais."],
  ["Funciona no computador e no telemóvel?", "Sim. O FARPHA é responsivo e instalável como PWA, permitindo acesso em desktop, tablet e dispositivos móveis."],
  ["Posso cancelar a subscrição?", "Sim. Plus e Pro incluem 30 dias de teste e podem ser cancelados; a gestão comercial é apresentada antes da confirmação da cobrança."],
];

export default function MarketingSite({ onEnter }: Props) {
  const [menu, setMenu] = useState(false); const [faq, setFaq] = useState<number>();
  return <main className="min-h-dvh overflow-x-hidden bg-[#f7f9f6] text-[#10271a]">
    <a href="#conteudo" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[200] focus:rounded-xl focus:bg-[#173c2a] focus:px-4 focus:py-3 focus:text-white">Saltar para o conteúdo</a>
    <nav className="sticky top-0 z-50 border-b border-[#173c2a]/10 bg-[#f7f9f6]/90 backdrop-blur-xl" aria-label="Navegação principal"><div className="mx-auto flex h-20 max-w-[1320px] items-center justify-between px-5 lg:px-8"><a href="#inicio" aria-label="FARPHA — Página inicial"><FarphaLogo eager className="h-12 w-auto max-w-[190px]"/></a><div className="hidden items-center gap-7 text-sm font-bold text-[#52645a] lg:flex"><a href="#plataforma" className="hover:text-[#173c2a]">Plataforma</a><a href="#mapa" className="hover:text-[#173c2a]">Mapa</a><a href="#modulos" className="hover:text-[#173c2a]">Módulos</a><a href="#seguranca" className="hover:text-[#173c2a]">Segurança</a><a href="#planos" className="hover:text-[#173c2a]">Planos</a><button onClick={onEnter} className="rounded-xl border border-[#214f39]/20 px-4 py-2.5 text-[#173c2a] hover:bg-white">Entrar</button><button onClick={onEnter} className="rounded-xl bg-[#173c2a] px-5 py-3 text-white shadow-lg shadow-emerald-950/15 hover:bg-[#214f39]">Começar agora</button></div><button onClick={() => setMenu(v => !v)} className="farpha-touch-target grid place-items-center rounded-xl border border-[#173c2a]/15 lg:hidden" aria-label={menu ? "Fechar menu" : "Abrir menu"} aria-expanded={menu}>{menu ? <X/> : <Menu/>}</button></div>{menu ? <div className="border-t bg-white p-4 lg:hidden"><div className="grid gap-1">{[["Plataforma","#plataforma"],["Mapa","#mapa"],["Módulos","#modulos"],["Segurança","#seguranca"],["Planos","#planos"]].map(([label,href]) => <a key={label} href={href} onClick={() => setMenu(false)} className="rounded-xl px-4 py-3 font-bold">{label}</a>)}<button onClick={onEnter} className="mt-2 rounded-xl bg-[#173c2a] px-4 py-3 font-black text-white">Entrar no FARPHA</button></div></div> : null}</nav>

    <div id="conteudo"><section id="inicio" className="relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_82%_20%,rgba(167,226,46,.22),transparent_29%),radial-gradient(circle_at_10%_80%,rgba(39,101,69,.10),transparent_30%)]"/><div className="relative mx-auto grid min-h-[760px] max-w-[1320px] items-center gap-14 px-5 py-20 lg:grid-cols-[.95fr_1.05fr] lg:px-8"><div><span className="inline-flex items-center gap-2 rounded-full border border-[#214f39]/15 bg-white px-3 py-2 text-xs font-black uppercase tracking-[.16em] text-[#276545] shadow-sm"><Sprout size={15}/> Sistema operacional para agricultura</span><h1 className="mt-7 max-w-3xl text-5xl font-black leading-[.97] tracking-[-.055em] sm:text-6xl xl:text-[76px]">A sua operação agrícola, conectada ao mapa e pronta para decidir.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#5f7066]">O FARPHA reúne explorações, talhões, clima, missões, custos, máquinas, conformidade e inteligência numa plataforma criada para transformar dados dispersos em trabalho claro.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={onEnter} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#173c2a] px-6 py-4 font-black text-white shadow-xl shadow-emerald-950/15 hover:-translate-y-0.5 hover:bg-[#214f39]">Começar no FARPHA <ArrowRight size={19}/></button><a href="#mapa" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-[#173c2a]/15 bg-white px-6 py-4 font-black text-[#173c2a] hover:border-[#276545]">Ver como funciona <ChevronRight size={18}/></a></div><div className="mt-8 grid max-w-xl grid-cols-2 gap-3 text-sm sm:grid-cols-3">{[[ShieldCheck,"Acesso protegido"],[Map,"Mapa integrado"],[Zap,"Decisões rápidas"]].map(([Icon,label]) => { const C = Icon as typeof ShieldCheck; return <span key={String(label)} className="flex items-center gap-2 font-bold text-[#52645a]"><C size={17} className="text-[#377d57]"/>{String(label)}</span>; })}</div></div><PlatformPreview/></div></section>

    <section className="border-y border-[#173c2a]/10 bg-white"><div className="mx-auto grid max-w-[1320px] grid-cols-2 gap-px px-5 py-8 sm:grid-cols-4 lg:px-8">{[["Um centro","para toda a operação"],["Mapa vivo","com contexto agrícola"],["40+ áreas","numa plataforma"],["PC e mobile","experiência responsiva"]].map(([value,label]) => <div key={value} className="p-4 text-center"><p className="text-xl font-black text-[#173c2a]">{value}</p><p className="mt-1 text-xs text-[#718078]">{label}</p></div>)}</div></section>

    <section id="plataforma" className="py-24"><div className="mx-auto max-w-[1320px] px-5 lg:px-8"><SectionTitle eyebrow="O que é o FARPHA" title="Mais do que gestão: uma visão operacional completa da exploração." text="Cada módulo acrescenta contexto ao mesmo fluxo de trabalho. O utilizador deixa de alternar entre folhas, mapas e sistemas isolados para trabalhar com uma única fonte organizada."/><div className="mt-12 grid gap-5 lg:grid-cols-3">{[[Layers3,"Centralizar","Explorações, talhões, documentos, máquinas, custos e operações ficam organizados num ambiente comum."],[Activity,"Acompanhar","Indicadores, alertas, prazos, riscos e tarefas tornam o estado da operação visível a cada momento."],[TrendingUp,"Decidir","O contexto espacial e operacional ajuda a transformar informação em prioridades e ações explicáveis."]].map(([Icon,title,text],index) => { const C=Icon as typeof Layers3; return <article key={String(title)} className="rounded-3xl border border-[#173c2a]/10 bg-white p-7 shadow-sm"><span className="text-xs font-black text-[#8bbf20]">0{index+1}</span><C className="mt-5 text-[#276545]" size={30}/><h3 className="mt-5 text-xl font-black">{String(title)}</h3><p className="mt-3 text-sm leading-7 text-[#66756c]">{String(text)}</p></article>; })}</div></div></section>

    <section id="mapa" className="overflow-hidden bg-[#07140d] py-24 text-white"><div className="mx-auto grid max-w-[1320px] gap-14 px-5 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#a7e22e]">O mapa no centro</p><h2 className="mt-4 text-4xl font-black leading-tight tracking-[-.04em] text-white md:text-5xl">Veja a exploração como um sistema, não como dados separados.</h2><p className="mt-6 text-lg leading-8 text-emerald-100/60">No FARPHA, o mapa relaciona onde algo acontece com o que precisa ser feito. Cada área pode ganhar contexto de cultura, clima, risco, missão, ambiente e histórico.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{mapLayers.map(item => <p key={item} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-sm font-bold"><Check className="text-[#a7e22e]" size={17}/>{item}</p>)}</div></div><MapCenterPreview/></div></section>

    <section id="modulos" className="py-24"><div className="mx-auto max-w-[1320px] px-5 lg:px-8"><SectionTitle eyebrow="Tudo o que a aplicação oferece" title="Módulos que acompanham a operação do campo à gestão." text="Comece pelo que precisa hoje e expanda a utilização sem perder o histórico ou o contexto da exploração."/><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{modules.map(({icon:Icon,title,text}) => <article key={title} className="group rounded-2xl border border-[#173c2a]/10 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-[#92c925]/50 hover:shadow-xl"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#edf6e6] text-[#276545] group-hover:bg-[#173c2a] group-hover:text-[#a7e22e]"><Icon size={24}/></span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66756c]">{text}</p></article>)}</div></div></section>

    <section className="bg-[#edf3ee] py-24"><div className="mx-auto max-w-[1320px] px-5 lg:px-8"><SectionTitle eyebrow="Como o trabalho flui" title="Da observação à ação, sem perder contexto." text="Um fluxo simples ajuda equipas e responsáveis a trabalhar sobre a mesma informação."/><div className="mt-12 grid gap-4 lg:grid-cols-4">{[[MapPinned,"Localize","Cadastre a exploração e organize talhões no mapa."],[CloudSun,"Observe","Reúna clima, risco, solo, ambiente e indicadores."],[ClipboardCheck,"Planeie","Converta necessidades em missões e ordens de trabalho."],[PackageCheck,"Comprove","Registe execução, custos, documentos e rastreabilidade."]].map(([Icon,title,text],index)=>{const C=Icon as typeof MapPinned;return <article key={String(title)} className="relative rounded-3xl bg-white p-6 shadow-sm"><span className="absolute right-5 top-4 text-4xl font-black text-[#edf3ee]">{index+1}</span><C className="text-[#276545]" size={26}/><h3 className="mt-6 font-black">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-[#66756c]">{String(text)}</p></article>})}</div></div></section>

    <section id="seguranca" className="py-24"><div className="mx-auto grid max-w-[1320px] gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#276545]">Segurança e continuidade</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] md:text-5xl">A conta e os dados da exploração merecem proteção real.</h2><p className="mt-6 text-lg leading-8 text-[#66756c]">Autenticação Supabase, recuperação por email, segundo fator, perfis de acesso e políticas RLS ajudam a proteger cada sessão e separar dados.</p><button onClick={onEnter} className="mt-8 inline-flex items-center gap-2 font-black text-[#276545]">Acessar conta segura <ArrowRight size={18}/></button></div><div className="grid gap-3">{[[ShieldCheck,"Autenticação e MFA","Login protegido, recuperação de palavra-passe e segundo fator TOTP."],[Layers3,"Permissões por perfil","Funções owner, manager, operator e viewer para organizar responsabilidades."],[Waves,"Segurança em nível de linha","Políticas RLS no Supabase limitam o acesso aos dados autenticados da exploração."],[PackageCheck,"Diagnóstico e continuidade","Verificações de produção, PWA e recursos de backup ajudam a reduzir interrupções."]].map(([Icon,title,text])=>{const C=Icon as typeof ShieldCheck;return <article key={String(title)} className="flex gap-4 rounded-2xl border border-[#173c2a]/10 bg-white p-5 shadow-sm"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#edf6e6] text-[#276545]"><C size={22}/></span><div><h3 className="font-black">{String(title)}</h3><p className="mt-1 text-sm leading-6 text-[#66756c]">{String(text)}</p></div></article>})}</div></div></section>

    <section id="planos" className="bg-[#0a1710] py-24 text-white"><div className="mx-auto max-w-[1180px] px-5 lg:px-8"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-[#a7e22e]">Planos FARPHA</p><h2 className="mt-4 text-4xl font-black text-white md:text-5xl">Comece com clareza. Evolua com a operação.</h2><p className="mx-auto mt-5 max-w-2xl text-emerald-100/60">Plus e Pro incluem 30 dias de teste. Cancele quando precisar.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{plans.map(plan => <article key={plan.name} className={`relative rounded-3xl border p-7 ${plan.featured ? "border-[#a7e22e] bg-[#10271a] shadow-[0_0_50px_rgba(167,226,46,.12)]" : "border-white/10 bg-white/[.04]"}`}>{plan.featured ? <span className="absolute -top-3 left-6 rounded-full bg-[#a7e22e] px-3 py-1 text-xs font-black text-[#10271a]">Mais escolhido</span> : null}<p className="font-black text-[#a7e22e]">{plan.name}</p><p className="mt-3 text-4xl font-black text-white">{plan.price}<span className="text-sm font-medium text-emerald-100/45">{plan.price !== "€0" ? "/mês" : ""}</span></p><p className="mt-4 min-h-12 text-sm leading-6 text-emerald-100/55">{plan.text}</p><div className="mt-6 space-y-3">{plan.items.map(item => <p key={item} className="flex gap-2 text-sm font-semibold"><Check className="text-[#a7e22e]" size={17}/>{item}</p>)}</div><button onClick={onEnter} className={`mt-8 w-full rounded-xl px-4 py-3 font-black ${plan.featured ? "bg-[#a7e22e] text-[#10271a]" : "border border-white/15 text-white hover:bg-white/5"}`}>Começar com {plan.name}</button></article>)}</div></div></section>

    <section className="py-24"><div className="mx-auto max-w-[900px] px-5"><SectionTitle centered eyebrow="Perguntas frequentes" title="Antes de começar, saiba o essencial."/><div className="mt-10 divide-y divide-[#173c2a]/10 rounded-3xl border border-[#173c2a]/10 bg-white px-5 shadow-sm">{faqs.map(([question,answer],index)=><article key={question}><button onClick={() => setFaq(faq === index ? undefined : index)} className="flex w-full items-center justify-between gap-4 py-5 text-left font-black" aria-expanded={faq===index}>{question}<ChevronDown className={`shrink-0 transition ${faq===index ? "rotate-180" : ""}`}/></button>{faq===index ? <p className="pb-5 pr-10 text-sm leading-7 text-[#66756c]">{answer}</p> : null}</article>)}</div></div></section>

    <section className="px-5 pb-24"><div className="mx-auto max-w-[1320px] overflow-hidden rounded-[32px] bg-[radial-gradient(circle_at_85%_20%,rgba(167,226,46,.22),transparent_28%),#173c2a] px-6 py-14 text-center text-white md:px-12"><Leaf className="mx-auto text-[#a7e22e]" size={36}/><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-black leading-tight text-white md:text-5xl">Transforme a exploração numa operação conectada.</h2><p className="mx-auto mt-5 max-w-2xl text-emerald-100/65">Entre no FARPHA e comece a organizar mapa, trabalho, riscos e decisões no mesmo ambiente.</p><button onClick={onEnter} className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-[#a7e22e] px-7 py-4 font-black text-[#10271a]">Começar agora <ArrowRight size={19}/></button></div></section>
    </div>
    <footer className="border-t border-white/10 bg-[#06100b] py-10 text-emerald-100/55"><div className="mx-auto flex max-w-[1320px] flex-col gap-6 px-5 sm:flex-row sm:items-center sm:justify-between lg:px-8"><FarphaLogo className="h-12 w-auto brightness-0 invert"/><div className="text-xs"><p>FARPHA · Intelligence for Agriculture</p><p className="mt-1">Plataforma operacional para agricultura inteligente e responsável.</p></div><button onClick={onEnter} className="text-left text-sm font-black text-[#a7e22e] sm:text-right">Entrar na plataforma →</button></div></footer>
  </main>;
}

function SectionTitle({ eyebrow, title, text, centered=false }: { eyebrow:string; title:string; text?:string; centered?:boolean }) { return <div className={centered ? "text-center" : ""}><p className="text-xs font-black uppercase tracking-[.2em] text-[#276545]">{eyebrow}</p><h2 className={`mt-4 text-4xl font-black leading-tight tracking-[-.04em] md:text-5xl ${centered ? "mx-auto max-w-3xl" : "max-w-4xl"}`}>{title}</h2>{text ? <p className={`mt-5 max-w-3xl text-lg leading-8 text-[#66756c] ${centered ? "mx-auto" : ""}`}>{text}</p> : null}</div>; }
function PlatformPreview(){return <div className="relative mx-auto w-full max-w-[620px]"><div className="absolute -inset-10 rounded-full bg-[#a7e22e]/15 blur-3xl"/><div className="relative overflow-hidden rounded-[30px] border border-white/70 bg-[#07140d] p-3 shadow-[0_45px_110px_rgba(18,53,36,.28)]"><div className="flex items-center justify-between border-b border-white/10 px-3 py-2"><div className="flex gap-2"><i className="h-2.5 w-2.5 rounded-full bg-red-400"/><i className="h-2.5 w-2.5 rounded-full bg-amber-300"/><i className="h-2.5 w-2.5 rounded-full bg-emerald-400"/></div><span className="text-[9px] font-bold uppercase tracking-[.18em] text-white/35">Centro operacional</span></div><div className="grid gap-3 p-3 sm:grid-cols-[105px_1fr]"><aside className="hidden rounded-2xl bg-[#0d2417] p-3 sm:block"><FarphaLogo compact className="h-9 w-9"/><div className="mt-5 space-y-2">{[1,2,3,4,5,6].map(x=><div key={x} className={`h-7 rounded-lg ${x===1 ? "bg-[#a7e22e]/80" : "bg-white/[.06]"}`}/>)}</div></aside><div><div className="grid grid-cols-3 gap-2">{[["Saúde","92"],["Operações","12"],["Alertas","3"]].map(([x,v])=><div key={x} className="rounded-xl bg-white/[.06] p-3"><p className="text-[9px] text-emerald-100/40">{x}</p><p className="mt-1 text-xl font-black text-white">{v}</p></div>)}</div><div className="relative mt-3 h-80 overflow-hidden rounded-2xl bg-[radial-gradient(circle_at_60%_40%,#315d3c,#0b2114_62%)]"><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(255,255,255,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.12)_1px,transparent_1px)] [background-size:34px_34px]"/><div className="absolute left-[18%] top-[20%] h-40 w-52 rotate-[-8deg] rounded-[42%_58%_53%_47%] border-2 border-[#a7e22e] bg-[#a7e22e]/20 shadow-[0_0_40px_rgba(167,226,46,.16)]"/><span className="absolute left-[53%] top-[43%] grid h-10 w-10 place-items-center rounded-full bg-[#a7e22e] text-[#10271a] shadow-lg"><MapPinned size={20}/></span><div className="absolute bottom-3 left-3 right-3 grid grid-cols-3 gap-2">{["Clima","Missões","Custos"].map(x=><span key={x} className="rounded-lg bg-[#07140d]/80 px-2 py-2 text-center text-[9px] font-bold text-white/60 backdrop-blur">{x}</span>)}</div></div></div></div></div></div>}
function MapCenterPreview(){return <div className="relative min-h-[560px] overflow-hidden rounded-[30px] border border-white/10 bg-[#0d2417] shadow-2xl"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.12)_1px,transparent_1px)] [background-size:48px_48px]"/><div className="absolute left-[12%] top-[17%] h-[48%] w-[55%] rotate-[-5deg] rounded-[38%_62%_50%_50%] border-2 border-[#a7e22e] bg-[#a7e22e]/14"/><div className="absolute right-5 top-5 w-48 rounded-2xl border border-white/10 bg-[#07140d]/85 p-4 backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-wider text-white/40">Camadas ativas</p>{["Talhões","Clima","Operações"].map(x=><p key={x} className="mt-3 flex items-center justify-between text-xs font-bold text-white/75">{x}<span className="h-2 w-2 rounded-full bg-[#a7e22e]"/></p>)}</div><div className="absolute bottom-5 left-5 right-5 grid gap-3 sm:grid-cols-3">{[[Activity,"Saúde","92%"],[CloudSun,"Risco","Baixo"],[ClipboardCheck,"Ativas","12"]].map(([Icon,l,v])=>{const C=Icon as typeof Activity;return <div key={String(l)} className="rounded-xl border border-white/10 bg-[#07140d]/85 p-3 backdrop-blur"><C className="text-[#a7e22e]" size={17}/><p className="mt-3 text-[9px] text-white/40">{String(l)}</p><p className="font-black text-white">{String(v)}</p></div>})}</div></div>}
