import { useState, type ComponentType } from "react";
import { ArrowRight, Bot, Check, ChevronDown, ClipboardCheck, CloudSun, Coins, FileCheck2, Layers3, MapPinned, Menu, Play, Satellite, ShieldCheck, Sprout, Tractor, X } from "lucide-react";
import FarphaLogo from "../../components/brand/FarphaLogo";
import heroImage from "../../assets/marketing/farpha-agriculture-hero-v2.webp";

type Props = { onEnter: () => void };
type Solution = { icon: ComponentType<{ size?: number; className?: string }>; title: string; text: string; link: string };

const solutions: Solution[] = [
  { icon: MapPinned, title: "Planear a exploração", text: "Desenhe limites, organize propriedades e mantenha culturas, áreas e histórico ligados ao lugar certo.", link: "Explorações e talhões" },
  { icon: ClipboardCheck, title: "Executar o trabalho", text: "Transforme necessidades em missões, ordens e prioridades claras para a equipa no campo.", link: "Operações e missões" },
  { icon: CloudSun, title: "Antecipar riscos", text: "Cruze previsão, água, incêndio, solo e ambiente com o contexto de cada parcela.", link: "Clima e risco" },
  { icon: Satellite, title: "Trabalhar com precisão", text: "Use observações, índices de vegetação e inteligência espacial para intervir onde é necessário.", link: "Agricultura de precisão" },
  { icon: Tractor, title: "Controlar recursos", text: "Acompanhe máquinas, inspeções, inventário, produtos e movimentos essenciais da exploração.", link: "Máquinas e inventário" },
  { icon: Coins, title: "Medir desempenho", text: "Relacione custos, produtividade e atividade para compreender o resultado real da operação.", link: "Gestão e resultados" },
];

const plans = [
  { name: "Free", price: "€0", description: "Comece a organizar a exploração.", items: ["Mapa e explorações", "Talhões e dados essenciais", "Acesso em PC e mobile"] },
  { name: "Plus", price: "€19,90", description: "Coordene o trabalho agrícola.", items: ["Tudo do Free", "Operações, clima e alertas", "Custos e relatórios"], featured: true },
  { name: "Pro", price: "€49,90", description: "Ative toda a capacidade FARPHA.", items: ["Toda a plataforma", "Precisão e inteligência", "Automação e conformidade"] },
];

export default function MarketingSiteV2({ onEnter }: Props) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [question, setQuestion] = useState<number>();
  const nav = [["Soluções", "#solucoes"], ["Mapa", "#mapa"], ["Plataforma", "#plataforma"], ["Segurança", "#seguranca"], ["Planos", "#planos"]];

  return <main className="min-h-dvh overflow-x-hidden bg-[#f5f6f2] text-[#132419]">
    <a href="#conteudo" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:bg-white focus:p-3">Saltar para o conteúdo</a>
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/15 bg-[#07150d]/90 text-white backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 lg:px-10">
        <a href="#inicio" aria-label="FARPHA — início" className="rounded-lg bg-white px-3 py-1.5"><FarphaLogo eager className="h-10 w-auto max-w-[170px]"/></a>
        <nav className="hidden items-center gap-7 text-sm font-bold lg:flex" aria-label="Navegação principal">{nav.map(([label, href]) => <a key={label} href={href} className="text-white/75 transition hover:text-white">{label}</a>)}</nav>
        <div className="hidden items-center gap-3 lg:flex"><button onClick={onEnter} className="px-4 py-3 text-sm font-black">Entrar</button><button onClick={onEnter} className="rounded-sm bg-[#b5db21] px-5 py-3 text-sm font-black text-[#102116] hover:bg-[#c8eb3b]">Experimentar grátis</button></div>
        <button onClick={() => setMenuOpen(value => !value)} className="grid h-11 w-11 place-items-center border border-white/20 lg:hidden" aria-label="Abrir menu">{menuOpen ? <X/> : <Menu/>}</button>
      </div>
      {menuOpen && <div className="border-t border-white/10 bg-[#07150d] p-5 lg:hidden">{nav.map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)} className="block border-b border-white/10 py-4 font-bold">{label}</a>)}<button onClick={onEnter} className="mt-5 w-full bg-[#b5db21] p-4 font-black text-[#102116]">Entrar no FARPHA</button></div>}
    </header>

    <div id="conteudo">
      <section id="inicio" className="relative flex min-h-[800px] items-end overflow-hidden bg-[#07150d] pt-20 text-white">
        <img src={heroImage} alt="Exploração agrícola portuguesa acompanhada através de tecnologia" className="absolute inset-0 h-full w-full object-cover"/>
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,15,8,.94)_0%,rgba(3,15,8,.72)_38%,rgba(3,15,8,.15)_72%),linear-gradient(0deg,rgba(3,15,8,.75),transparent_55%)]"/>
        <div className="relative mx-auto w-full max-w-[1440px] px-5 pb-20 pt-28 lg:px-10 lg:pb-28">
          <p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-[#c6e842]"><Sprout size={16}/> Intelligence for Agriculture</p>
          <h1 className="mt-6 max-w-[820px] text-5xl font-black leading-[.94] tracking-[-.055em] text-white sm:text-6xl lg:text-[88px]">Veja toda a exploração. Decida com confiança.</h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-white/75 lg:text-xl">O FARPHA é o centro operacional agrícola que liga mapa, talhões, trabalho, clima, recursos, custos e inteligência numa visão única da sua operação.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={onEnter} className="inline-flex items-center justify-center gap-2 bg-[#b5db21] px-7 py-4 font-black text-[#102116] transition hover:bg-[#c8eb3b]">Começar 30 dias grátis <ArrowRight size={19}/></button><a href="#mapa" className="inline-flex items-center justify-center gap-2 border border-white/35 bg-black/15 px-7 py-4 font-black text-white backdrop-blur"><Play size={17}/> Descobrir a plataforma</a></div>
          <div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/20 pt-6 text-sm font-bold text-white/70"><span>Sem cartão durante o teste</span><span>PC, tablet e telemóvel</span><span>Dados protegidos</span></div>
        </div>
      </section>

      <section className="bg-white py-10"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 sm:grid-cols-3 lg:px-10"><Metric value="Uma visão" label="para campo, equipa e gestão"/><Metric value="Mapa vivo" label="como centro de toda a operação"/><Metric value="40+ áreas" label="agrícolas integradas na plataforma"/></div></section>

      <section id="solucoes" className="py-24 lg:py-32"><div className="mx-auto max-w-[1440px] px-5 lg:px-10">
        <Heading eyebrow="Soluções para cada decisão" title="Tecnologia que acompanha o trabalho agrícola de ponta a ponta." text="Em vez de ferramentas separadas, o FARPHA organiza cada etapa da exploração num fluxo contínuo e compreensível."/>
        <div className="mt-14 grid gap-px overflow-hidden border border-[#163523]/15 bg-[#163523]/15 md:grid-cols-2 xl:grid-cols-3">{solutions.map(({icon: Icon, title, text, link}) => <article key={title} className="group bg-white p-8 lg:p-10"><Icon size={33} className="text-[#2c7048]"/><h3 className="mt-7 text-2xl font-black">{title}</h3><p className="mt-4 min-h-20 leading-7 text-[#617067]">{text}</p><p className="mt-7 inline-flex items-center gap-2 text-sm font-black text-[#276545] group-hover:gap-3">{link} <ArrowRight size={17}/></p></article>)}</div>
      </div></section>

      <section id="mapa" className="bg-[#07150d] py-24 text-white lg:py-32"><div className="mx-auto grid max-w-[1440px] gap-16 px-5 lg:grid-cols-[.82fr_1.18fr] lg:items-center lg:px-10">
        <div><p className="text-xs font-black uppercase tracking-[.22em] text-[#b5db21]">O coração do FARPHA</p><h2 className="mt-5 text-4xl font-black leading-[1.02] tracking-[-.045em] text-white lg:text-6xl">Tudo começa e volta ao mapa.</h2><p className="mt-6 text-lg leading-8 text-white/60">Localização sem contexto é apenas um ponto. O FARPHA transforma cada talhão numa unidade viva, ligada ao que existe, ao que aconteceu e ao que deve acontecer.</p><div className="mt-9 space-y-5">{[[Layers3,"Compreenda","Limites, culturas, solo, água, clima e satélite em camadas."],[ClipboardCheck,"Coordene","Missões, equipas, máquinas e alertas ligados a cada área."],[Bot,"Decida","Prioridades explicáveis a partir do contexto real da exploração."]].map(([Icon,title,text]) => { const C=Icon as typeof Layers3; return <div key={String(title)} className="flex gap-4 border-t border-white/15 pt-5"><C className="shrink-0 text-[#b5db21]"/><div><h3 className="font-black text-white">{String(title)}</h3><p className="mt-1 text-sm leading-6 text-white/55">{String(text)}</p></div></div>; })}</div></div>
        <MapStory/>
      </div></section>

      <section id="plataforma" className="py-24 lg:py-32"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><Heading eyebrow="Uma plataforma. Toda a operação." title="Do planeamento à comprovação, sem perder o fio da decisão."/><div className="mt-14 grid gap-8 lg:grid-cols-4">{[["01","Preparar","Cadastre explorações, limites, culturas e recursos."],["02","Observar","Reúna clima, risco, solo, satélite e ocorrências."],["03","Agir","Crie missões, atribua trabalho e acompanhe execução."],["04","Comprovar","Consolide custos, histórico, documentos e rastreabilidade."]].map(([number,title,text]) => <article key={number} className="border-t-4 border-[#b5db21] pt-6"><p className="text-sm font-black text-[#2c7048]">{number}</p><h3 className="mt-7 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-[#617067]">{text}</p></article>)}</div></div></section>

      <section id="seguranca" className="bg-[#e8eee8] py-24"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-10"><div><Heading eyebrow="Confiança operacional" title="Os seus dados agrícolas pertencem à sua operação." text="A arquitetura FARPHA combina autenticação Supabase, recuperação por email, segundo fator, perfis de acesso e políticas RLS para separar e proteger informação."/><button onClick={onEnter} className="mt-8 inline-flex items-center gap-2 bg-[#173c2a] px-6 py-4 font-black text-white">Entrar com segurança <ArrowRight size={18}/></button></div><div className="grid gap-px bg-[#173c2a]/15 sm:grid-cols-2">{[[ShieldCheck,"Autenticação e MFA"],[Layers3,"Permissões por função"],[FileCheck2,"Rastreabilidade e auditoria"],[Bot,"Assistência contextual"]].map(([Icon,title]) => { const C=Icon as typeof ShieldCheck; return <div key={String(title)} className="bg-white p-7"><C className="text-[#2c7048]" size={28}/><h3 className="mt-5 font-black">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-[#617067]">Proteção integrada e controlo concebidos para continuidade operacional.</p></div>; })}</div></div></section>

      <section id="planos" className="py-24 lg:py-32"><div className="mx-auto max-w-[1180px] px-5"><Heading centered eyebrow="Planos FARPHA" title="Comece agora. Cresça quando precisar." text="Experimente Plus ou Pro durante 30 dias. Cancele quando quiser."/><div className="mt-14 grid gap-5 md:grid-cols-3">{plans.map(plan => <article key={plan.name} className={`relative border p-8 ${plan.featured ? "border-[#2c7048] bg-[#10261a] text-white shadow-2xl" : "border-[#173c2a]/15 bg-white"}`}>{plan.featured && <span className="absolute right-0 top-0 bg-[#b5db21] px-3 py-2 text-xs font-black text-[#102116]">RECOMENDADO</span>}<p className="font-black text-[#6f9e16]">{plan.name}</p><p className="mt-4 text-4xl font-black">{plan.price}<span className="text-sm font-medium opacity-50">{plan.price !== "€0" ? "/mês" : ""}</span></p><p className="mt-3 text-sm opacity-65">{plan.description}</p><div className="mt-8 space-y-4">{plan.items.map(item => <p key={item} className="flex gap-2 text-sm font-bold"><Check size={17} className="text-[#91bd24]"/>{item}</p>)}</div><button onClick={onEnter} className={`mt-9 w-full p-4 font-black ${plan.featured ? "bg-[#b5db21] text-[#102116]" : "border border-[#173c2a]/20"}`}>Escolher {plan.name}</button></article>)}</div></div></section>

      <section className="bg-white py-24"><div className="mx-auto max-w-[900px] px-5"><Heading centered eyebrow="Perguntas frequentes" title="Conheça o FARPHA antes de começar."/><div className="mt-10 border-y border-[#173c2a]/15">{[["O FARPHA substitui várias ferramentas?","Sim. A proposta é reunir contexto espacial, gestão operacional, riscos, recursos, custos, conformidade e inteligência no mesmo ambiente."],["Por que o mapa é central?","Porque liga cada decisão ao local onde ela acontece. Talhões, missões, clima, riscos, recursos e histórico deixam de ser informação isolada."],["Funciona no campo?","O FARPHA é responsivo e instalável como PWA para utilização em computador, tablet e telemóvel."],["Posso cancelar a subscrição?","Sim. Os planos pagos oferecem período experimental de 30 dias e podem ser cancelados."]].map(([q,a],index) => <article key={q} className="border-b border-[#173c2a]/15 last:border-0"><button onClick={() => setQuestion(question === index ? undefined : index)} className="flex w-full items-center justify-between gap-4 py-6 text-left text-lg font-black" aria-expanded={question === index}>{q}<ChevronDown className={`transition ${question === index ? "rotate-180" : ""}`}/></button>{question === index && <p className="max-w-3xl pb-6 leading-7 text-[#617067]">{a}</p>}</article>)}</div></div></section>

      <section className="relative overflow-hidden bg-[#173c2a] px-5 py-24 text-center text-white"><div className="absolute inset-0 opacity-10 [background-image:radial-gradient(circle_at_center,#b5db21_1px,transparent_1px)] [background-size:24px_24px]"/><div className="relative mx-auto max-w-4xl"><Sprout className="mx-auto text-[#b5db21]" size={38}/><h2 className="mt-6 text-4xl font-black leading-tight text-white lg:text-6xl">A exploração inteira, finalmente conectada.</h2><p className="mx-auto mt-6 max-w-2xl text-lg text-white/65">Comece pelo mapa. Organize o trabalho. Decida com uma visão completa.</p><button onClick={onEnter} className="mt-9 inline-flex items-center gap-2 bg-[#b5db21] px-8 py-4 font-black text-[#102116]">Experimentar o FARPHA <ArrowRight size={19}/></button></div></section>
    </div>

    <footer className="bg-[#06100a] py-12 text-white/60"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 md:grid-cols-[1fr_2fr_auto] md:items-center lg:px-10"><span className="inline-flex w-fit rounded bg-white px-3 py-2"><FarphaLogo className="h-10 w-auto"/></span><div className="text-sm"><p className="font-bold text-white">FARPHA · Intelligence for Agriculture</p><p className="mt-2">O centro operacional para uma agricultura mais informada, eficiente e responsável.</p></div><button onClick={onEnter} className="font-black text-[#b5db21]">Entrar na plataforma →</button></div></footer>
  </main>;
}

function Heading({ eyebrow, title, text, centered=false }: { eyebrow:string; title:string; text?:string; centered?:boolean }) { return <div className={centered ? "text-center" : ""}><p className="text-xs font-black uppercase tracking-[.22em] text-[#2c7048]">{eyebrow}</p><h2 className={`mt-5 text-4xl font-black leading-[1.04] tracking-[-.045em] lg:text-6xl ${centered ? "mx-auto max-w-4xl" : "max-w-5xl"}`}>{title}</h2>{text && <p className={`mt-6 max-w-3xl text-lg leading-8 text-[#617067] ${centered ? "mx-auto" : ""}`}>{text}</p>}</div>; }
function Metric({ value, label }: { value:string; label:string }) { return <div className="border-l-4 border-[#b5db21] pl-5"><p className="text-2xl font-black">{value}</p><p className="mt-1 text-sm text-[#617067]">{label}</p></div>; }
function MapStory() { return <div className="relative min-h-[620px] overflow-hidden border border-white/15 bg-[#10291b] shadow-2xl"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.1)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.1)_1px,transparent_1px)] [background-size:44px_44px]"/><div className="absolute left-[12%] top-[14%] h-[57%] w-[62%] rotate-[-7deg] rounded-[38%_62%_50%_46%] border-2 border-[#b5db21] bg-[#b5db21]/15 shadow-[0_0_70px_rgba(181,219,33,.12)]"/><span className="absolute left-[48%] top-[40%] grid h-14 w-14 place-items-center rounded-full bg-[#b5db21] text-[#102116]"><MapPinned size={27}/></span><div className="absolute right-5 top-5 w-52 border border-white/15 bg-[#07150d]/90 p-5 backdrop-blur"><p className="text-xs font-black uppercase tracking-wider text-white/40">Camadas ativas</p>{["Talhões","Clima e risco","Operações","Satélite"].map(item => <p key={item} className="mt-4 flex justify-between text-sm font-bold">{item}<i className="h-2.5 w-2.5 rounded-full bg-[#b5db21]"/></p>)}</div><div className="absolute bottom-5 left-5 right-5 grid gap-2 sm:grid-cols-3">{[["Saúde vegetal","92%"],["Missões ativas","12"],["Risco atual","Baixo"]].map(([label,value]) => <div key={label} className="border border-white/15 bg-[#07150d]/90 p-4 backdrop-blur"><p className="text-xs text-white/45">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>)}</div></div>; }
