import { useMemo, useState } from "react";
import { Download, Trophy } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { listHarvestRecords } from "../../harvest/services/harvestStorage";
import { summarizeHarvest } from "../../harvest/utils/harvest";
import { downloadProductivityCsv, filterProductivityRecords, groupProductivity, type ProductivityDimension, type ProductivityFilters } from "../utils/productivity";

const initialFilters: ProductivityFilters = { farm: "", crop: "", campaign: "", startDate: "", endDate: "" };
const inputClass = "h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";
const dimensionLabels: Record<ProductivityDimension, string> = { crop: "Cultura", field: "Talhão", campaign: "Campanha" };

export default function ProductivityDashboardPage() {
  const [records] = useState(() => listHarvestRecords()); const [filters, setFilters] = useState(initialFilters); const [dimension, setDimension] = useState<ProductivityDimension>("crop");
  const filtered = useMemo(() => filterProductivityRecords(records, filters), [records, filters]); const groups = useMemo(() => groupProductivity(filtered, dimension), [filtered, dimension]); const summary = summarizeHarvest(filtered); const maxYield = Math.max(1, ...groups.map((group) => group.yieldTonsPerHa));
  return <div className="mx-auto max-w-[1400px] space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 66 · Comparação de resultados</p><h1 className="mt-1 text-3xl font-black">Dashboard de produtividade</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Comparações calculadas exclusivamente a partir das colheitas registadas pelo utilizador.</p></div><Button onClick={() => downloadProductivityCsv(groups, dimension, new Date().toISOString())}><Download size={18}/> Exportar comparação CSV</Button></header>
    <Card className="p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><input className={inputClass} placeholder="Exploração" value={filters.farm} onChange={(e) => setFilters({ ...filters, farm: e.target.value })}/><input className={inputClass} placeholder="Cultura" value={filters.crop} onChange={(e) => setFilters({ ...filters, crop: e.target.value })}/><input className={inputClass} placeholder="Campanha" value={filters.campaign} onChange={(e) => setFilters({ ...filters, campaign: e.target.value })}/><input type="date" className={inputClass} value={filters.startDate} onChange={(e) => setFilters({ ...filters, startDate: e.target.value })}/><input type="date" className={inputClass} value={filters.endDate} onChange={(e) => setFilters({ ...filters, endDate: e.target.value })}/></div><button type="button" onClick={() => setFilters(initialFilters)} className="mt-4 text-sm font-bold text-emerald-700">Limpar filtros</button></Card>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Colheitas analisadas</p><p className="mt-2 text-3xl font-black">{summary.records}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Produção bruta</p><p className="mt-2 text-3xl font-black">{summary.grossTons} t</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Produtividade média</p><p className="mt-2 text-3xl font-black">{summary.yieldTonsPerHa} t/ha</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Perdas</p><p className="mt-2 text-3xl font-black text-red-700">{summary.lossPercent}%</p></Card></section>
    <Card className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><h2 className="flex items-center gap-2 text-xl font-black"><Trophy className="text-amber-500"/> Ranking de produtividade</h2><div className="flex rounded-xl bg-slate-100 p-1">{(["crop", "field", "campaign"] as const).map((item) => <button type="button" key={item} onClick={() => setDimension(item)} className={`rounded-lg px-4 py-2 text-sm font-bold ${dimension === item ? "bg-white text-emerald-700 shadow-sm" : "text-slate-600"}`}>{dimensionLabels[item]}</button>)}</div></div>
      {groups.length === 0 ? <p className="py-12 text-center text-slate-500">Sem colheitas para comparar. Registe dados em Produção e Colheita.</p> : <div className="mt-6 space-y-4">{groups.map((group, index) => <article key={group.key} className="grid gap-3 rounded-xl border border-slate-200 p-4 lg:grid-cols-[42px_220px_1fr_130px]"><span className="grid h-9 w-9 place-items-center rounded-full bg-emerald-100 font-black text-emerald-700">{index + 1}</span><div><p className="font-black">{group.key}</p><p className="text-xs text-slate-500">{group.records} registos · {group.areaHa} ha</p></div><div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${(group.yieldTonsPerHa / maxYield) * 100}%` }}/></div><p className="mt-2 text-xs text-slate-500">{group.grossTons} t brutas · {group.marketableTons} t comercializáveis · {group.lossPercent}% perdas</p></div><p className="text-right text-xl font-black">{group.yieldTonsPerHa} <span className="text-xs text-slate-500">t/ha</span></p></article>)}</div>}
    </Card><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">As comparações refletem apenas os registos locais disponíveis e não constituem previsão de produtividade.</p>
  </div>;
}
