import { useEffect, useRef, useState, type FormEvent } from "react";
import { Bot, CheckCircle2, ChevronRight, Clock3, Headphones, Mail, MessageCircle, Phone, Plus, Send, ShieldCheck, Sparkles, Ticket, UserRound, X } from "lucide-react";
import { supportConfig } from "./supportConfig";

type Message = { id: number; author: "assistant" | "user"; text: string; path?: string; action?: string };
type SupportTicket = { id: string; subject: string; category: string; priority: string; description: string; status: "Aberto"; createdAt: string };
type Tab = "assistant" | "tickets" | "contact";

const TICKETS_KEY = "farpha-support-tickets-v1";
const quickActions = ["Começar no FARPHA", "Encontrar um módulo", "Resolver um problema", "Conta e segurança", "Planos e subscrição"];

function answerFor(question: string): Omit<Message, "id" | "author"> {
  const value = question.toLocaleLowerCase("pt-PT");
  if (/plano|preço|preco|subscri|cartão|cartao|teste/.test(value)) return { text: "Compare Free, Plus e Pro em Plano e subscrição. Os planos pagos incluem 30 dias de teste e podem ser cancelados pela conta.", path: "/configuracoes#subscricao", action: "Abrir planos" };
  if (/senha|palavra-passe|2fa|seguran|sessão|sessao/.test(value)) return { text: "Na área Segurança pode recuperar a palavra-passe por email, configurar MFA e rever sessões. Nunca partilhe códigos ou palavras-passe no apoio.", path: "/configuracoes#seguranca", action: "Abrir segurança" };
  if (/mapa|talhão|talhao|explora/.test(value)) return { text: "Comece por criar uma exploração. Depois desenhe ou importe os talhões; o mapa passa a relacionar clima, missões, riscos e histórico.", path: "/exploracoes", action: "Abrir explorações" };
  if (/clima|tempo|chuva|meteor/.test(value)) return { text: "Clima utiliza as coordenadas da exploração selecionada para apresentar previsão e alertas relevantes.", path: "/clima", action: "Abrir clima" };
  if (/custo|finance|despesa/.test(value)) return { text: "Registe custos por operação e consulte o consolidado no Relatório Financeiro.", path: "/custos", action: "Abrir custos" };
  if (/erro|problema|branco|carrega|diagn/.test(value)) return { text: "Execute primeiro o Diagnóstico. Se o problema continuar, crie um pedido com a página, a ação, o horário e a mensagem apresentada — sem dados sensíveis.", path: "/diagnostico", action: "Executar diagnóstico" };
  if (/humano|pessoa|agente|atendente|administrador|whatsapp|telefone/.test(value)) return { text: "Abra a área Equipa para falar com o administrador por WhatsApp, email ou telefone. Para questões técnicas, criar um pedido mantém o histórico organizado." };
  if (/começar|comecar|primeiro|início|inicio/.test(value)) return { text: "Fluxo recomendado: 1) crie uma exploração; 2) adicione talhões; 3) consulte clima e alertas; 4) registe operações; 5) reveja prioridades no Dashboard.", path: "/exploracoes", action: "Começar agora" };
  if (/módulo|modulo|encontrar|navegar/.test(value)) return { text: "Use Ctrl+K ou a pesquisa global para encontrar qualquer módulo. Também posso conduzi-lo se disser a tarefa que pretende realizar." };
  return { text: "Posso orientar tarefas, localizar módulos e preparar um diagnóstico. Diga o resultado que pretende obter ou crie um pedido para registar a situação com a equipa." };
}

function loadTickets(): SupportTicket[] {
  try { return JSON.parse(localStorage.getItem(TICKETS_KEY) || "[]") as SupportTicket[]; } catch { return []; }
}

export default function SupportAssistant() {
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState<Tab>("assistant");
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState<Message[]>([{ id: 1, author: "assistant", text: "Olá! Sou a Inteligência FARPHA. Posso orientar a utilização, localizar recursos, preparar um diagnóstico ou encaminhar para a equipa." }]);
  const [tickets, setTickets] = useState<SupportTicket[]>(loadTickets);
  const [creating, setCreating] = useState(false);
  const [createdId, setCreatedId] = useState("");
  const endRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const messageId = useRef(2);

  useEffect(() => { const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, []);
  useEffect(() => { if (open && tab === "assistant") window.setTimeout(() => inputRef.current?.focus(), 80); }, [open, tab]);
  useEffect(() => { endRef.current?.scrollIntoView({ block: "nearest" }); }, [messages.length]);

  function ask(text: string) {
    const clean = text.trim(); if (!clean) return;
    const base = messageId.current; messageId.current += 2;
    setMessages((current) => [...current, { id: base, author: "user", text: clean }, { id: base + 1, author: "assistant", ...answerFor(clean) }]);
    setQuestion("");
  }
  function submit(event: FormEvent) { event.preventDefault(); ask(question); }
  function navigate(path: string) { setOpen(false); window.location.assign(path); }
  function createTicket(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form);
    const ticket: SupportTicket = { id: `FAR-${Date.now().toString().slice(-8)}`, subject: String(data.get("subject")), category: String(data.get("category")), priority: String(data.get("priority")), description: String(data.get("description")), status: "Aberto", createdAt: new Date().toISOString() };
    const next = [ticket, ...tickets]; setTickets(next); localStorage.setItem(TICKETS_KEY, JSON.stringify(next)); setCreatedId(ticket.id); setCreating(false); form.reset();
  }
  const whatsapp = `https://wa.me/${supportConfig.whatsapp}?text=${encodeURIComponent("Olá, preciso de ajuda com o FARPHA.")}`;

  return <>
    <button type="button" onClick={() => setOpen(true)} className="fixed bottom-20 right-4 z-[var(--farpha-z-assistant)] flex min-h-14 items-center gap-2 rounded-2xl bg-[#173c2a] px-4 font-black text-white shadow-[0_18px_45px_rgba(7,35,20,.28)] transition hover:-translate-y-0.5 hover:bg-[#245b3e] sm:bottom-6 sm:right-6" aria-label="Abrir Centro de Ajuda FARPHA" aria-haspopup="dialog"><Headphones size={22}/><span className="hidden xl:inline">Ajuda e suporte</span></button>
    {open && <section role="dialog" aria-modal="true" aria-labelledby="support-title" className="fixed inset-2 z-[var(--farpha-z-assistant)] flex flex-col overflow-hidden rounded-3xl border border-[var(--farpha-border)] bg-[var(--farpha-surface)] shadow-[0_30px_100px_rgba(5,30,17,.35)] sm:inset-auto sm:bottom-5 sm:right-6 sm:h-[min(760px,calc(100dvh-2.5rem))] sm:w-[min(480px,calc(100vw-3rem))]">
      <header className="bg-[#102d1e] p-4 text-white"><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#b4e533] text-[#102d1e]"><Sparkles size={23}/></span><div className="min-w-0"><h2 id="support-title" className="font-black text-white">Centro de Ajuda FARPHA</h2><p className="truncate text-xs text-white/55">Inteligência, pedidos e atendimento</p></div></div><button onClick={() => setOpen(false)} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl hover:bg-white/10" aria-label="Fechar centro de ajuda"><X size={20}/></button></div>
        <nav className="mt-4 grid grid-cols-3 gap-1 rounded-xl bg-black/20 p-1" aria-label="Áreas do suporte">{[["assistant", "Inteligência", Bot], ["tickets", "Pedidos", Ticket], ["contact", "Equipa", UserRound]].map(([id, label, Icon]) => { const C = Icon as typeof Bot; return <button key={String(id)} onClick={() => setTab(id as Tab)} className={`flex min-h-11 items-center justify-center gap-1 rounded-lg px-1 text-[11px] font-black sm:text-xs ${tab === id ? "bg-white text-[#173c2a]" : "text-white/65 hover:text-white"}`} aria-current={tab === id ? "page" : undefined}><C size={15}/>{String(label)}</button>; })}</nav>
      </header>

      {tab === "assistant" && <><div className="min-h-0 flex-1 overflow-y-auto bg-[var(--farpha-background)] p-4"><div className="space-y-3">{messages.map((message) => <article key={message.id} className={`max-w-[90%] rounded-2xl p-3 text-sm leading-6 ${message.author === "user" ? "ml-auto bg-[#276545] text-white" : "border border-[var(--farpha-border)] bg-[var(--farpha-surface)] text-[var(--farpha-text)] shadow-sm"}`}><p>{message.text}</p>{message.path && <button onClick={() => navigate(message.path!)} className="mt-2 inline-flex items-center gap-1 font-black text-emerald-700">{message.action}<ChevronRight size={15}/></button>}</article>)}</div>{messages.length === 1 && <div className="mt-4 grid gap-2">{quickActions.map((item) => <button key={item} onClick={() => ask(item)} className="flex min-h-11 items-center justify-between rounded-xl border border-[var(--farpha-border)] bg-[var(--farpha-surface)] px-3 text-left text-xs font-bold text-[var(--farpha-text)] hover:border-emerald-500">{item}<ChevronRight size={15}/></button>)}</div>}<button onClick={() => { setTab("tickets"); setCreating(true); }} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-emerald-600/40 p-3 text-sm font-black text-emerald-700"><Ticket size={17}/>Ainda precisa de ajuda? Criar pedido</button><div ref={endRef}/></div>
        <form onSubmit={submit} className="border-t border-[var(--farpha-border)] bg-[var(--farpha-surface)] p-3"><div className="flex gap-2"><input ref={inputRef} value={question} onChange={(event) => setQuestion(event.target.value)} maxLength={300} placeholder="Descreva o que pretende fazer" aria-label="Pergunta para a Inteligência FARPHA" className="min-w-0 flex-1 rounded-xl border border-[var(--farpha-border)] bg-[var(--farpha-surface-muted)] px-3 py-3 text-sm text-[var(--farpha-text)] outline-none focus:border-emerald-500"/><button className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#276545] text-white" aria-label="Enviar pergunta"><Send size={18}/></button></div><p className="mt-2 flex items-start gap-1 text-[10px] text-[var(--farpha-text-muted)]"><ShieldCheck size={12} className="mt-0.5 shrink-0"/>Orientação local e privada. Não introduza palavras-passe ou dados bancários.</p></form></>}

      {tab === "tickets" && <div className="min-h-0 flex-1 overflow-y-auto p-4">{createdId && <div role="status" className="mb-4 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-900"><p className="flex items-center gap-2 font-black"><CheckCircle2 size={18}/>Pedido criado</p><p className="mt-1">Referência {createdId}. O histórico permanece neste dispositivo; use Equipa para o enviar ao administrador.</p></div>}<div className="flex items-center justify-between gap-3"><div><h3 className="font-black">Pedidos de suporte</h3><p className="text-xs text-[var(--farpha-text-muted)]">Registe e acompanhe situações técnicas.</p></div><button onClick={() => setCreating(!creating)} className="flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-[#173c2a] px-3 text-xs font-black text-white"><Plus size={16}/>Novo</button></div>
        {creating && <form onSubmit={createTicket} className="mt-4 grid gap-3 rounded-2xl border border-[var(--farpha-border)] bg-[var(--farpha-background)] p-4"><label className="text-xs font-bold">Assunto<input required name="subject" maxLength={100} className="mt-1.5 w-full rounded-xl border border-[var(--farpha-border)] bg-[var(--farpha-surface)] p-3 text-[var(--farpha-text)]"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Categoria<select name="category" className="mt-1.5 w-full rounded-xl border border-[var(--farpha-border)] bg-[var(--farpha-surface)] p-3 text-[var(--farpha-text)]"><option>Problema técnico</option><option>Conta e acesso</option><option>Subscrição</option><option>Dúvida de utilização</option><option>Sugestão</option></select></label><label className="text-xs font-bold">Prioridade<select name="priority" className="mt-1.5 w-full rounded-xl border border-[var(--farpha-border)] bg-[var(--farpha-surface)] p-3 text-[var(--farpha-text)]"><option>Normal</option><option>Alta</option><option>Urgente</option></select></label></div><label className="text-xs font-bold">Descrição<textarea required name="description" rows={4} maxLength={1200} placeholder="Página, ação e mensagem apresentada" className="mt-1.5 w-full resize-none rounded-xl border border-[var(--farpha-border)] bg-[var(--farpha-surface)] p-3 text-[var(--farpha-text)]"/></label><button className="rounded-xl bg-[#276545] p-3 font-black text-white">Guardar pedido</button></form>}
        <div className="mt-4 space-y-3">{tickets.length === 0 && !creating && <div className="rounded-2xl border border-dashed border-[var(--farpha-border)] p-8 text-center"><Ticket className="mx-auto text-[var(--farpha-text-muted)]"/><p className="mt-3 font-black">Ainda não existem pedidos</p></div>}{tickets.map((ticket) => <article key={ticket.id} className="rounded-2xl border border-[var(--farpha-border)] p-4"><div className="flex items-center justify-between gap-2"><p className="font-black">{ticket.subject}</p><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-800">{ticket.status}</span></div><p className="mt-2 text-xs text-[var(--farpha-text-muted)]">{ticket.id} · {ticket.category} · {ticket.priority}</p><p className="mt-2 line-clamp-2 text-sm">{ticket.description}</p></article>)}</div></div>}

      {tab === "contact" && <div className="min-h-0 flex-1 overflow-y-auto p-4"><div className="rounded-2xl bg-[#edf5e7] p-4"><h3 className="flex items-center gap-2 font-black text-[#173c2a]"><UserRound size={19}/>Falar com o administrador</h3><p className="mt-2 text-sm leading-6 text-[#52645a]">Use WhatsApp para orientação rápida, telefone para situações urgentes no horário de atendimento e email para assuntos que exigem documentos.</p></div><div className="mt-4 grid gap-3"><a href={whatsapp} target="_blank" rel="noreferrer" className="flex min-h-16 items-center gap-4 rounded-2xl border border-[var(--farpha-border)] p-4 hover:border-emerald-500"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><MessageCircle/></span><span><strong className="block">WhatsApp</strong><small className="text-[var(--farpha-text-muted)]">Iniciar conversa com o atendimento</small></span></a><a href={`mailto:${supportConfig.email}?subject=Ajuda%20FARPHA`} className="flex min-h-16 items-center gap-4 rounded-2xl border border-[var(--farpha-border)] p-4 hover:border-emerald-500"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-sky-100 text-sky-700"><Mail/></span><span className="min-w-0"><strong className="block break-all">{supportConfig.email}</strong><small className="text-[var(--farpha-text-muted)]">Resposta e envio de documentação</small></span></a><a href={`tel:${supportConfig.phoneHref}`} className="flex min-h-16 items-center gap-4 rounded-2xl border border-[var(--farpha-border)] p-4 hover:border-emerald-500"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-700"><Phone/></span><span><strong className="block">{supportConfig.phone}</strong><small className="text-[var(--farpha-text-muted)]">Atendimento telefónico</small></span></a></div><p className="mt-5 flex items-start gap-2 rounded-xl bg-[var(--farpha-background)] p-3 text-xs text-[var(--farpha-text-muted)]"><Clock3 size={16} className="shrink-0"/>{supportConfig.hours}. Configure os contactos VITE_SUPPORT_* antes da publicação.</p></div>}
    </section>}
  </>;
}
