import type { SoilEstimate, SoilProfile, SoilPropertyCode } from "../types/soil";
type ApiDepth = { label: string; values: { mean?: number | null; "Q0.05"?: number | null; "Q0.95"?: number | null } };
type ApiLayer = { name: SoilPropertyCode; unit_measure?: { d_factor?: number; target_units?: string; mapped_units?: string }; depths?: ApiDepth[] };
type ApiResponse = { properties?: { layers?: ApiLayer[] } };
const properties: SoilPropertyCode[] = ["phh2o", "soc", "clay", "sand", "silt", "nitrogen", "cec", "bdod"];
const depths = ["0-5cm", "5-15cm", "15-30cm"];
const convert = (value: number | null | undefined, factor: number) => value == null ? null : Number((value / factor).toFixed(2));
export function parseSoilGridsResponse(data: ApiResponse): SoilEstimate[] { return (data.properties?.layers ?? []).flatMap((layer) => { const factor = layer.unit_measure?.d_factor || 1; const unit = layer.unit_measure?.target_units || layer.unit_measure?.mapped_units || "Unidade não informada"; return (layer.depths ?? []).filter((depth) => depths.includes(depth.label)).map((depth) => ({ property: layer.name, depth: depth.label, mean: convert(depth.values.mean, factor), low: convert(depth.values["Q0.05"], factor), high: convert(depth.values["Q0.95"], factor), unit })); }); }
export async function fetchSoilProfile(latitude: number, longitude: number, signal?: AbortSignal): Promise<SoilProfile> { if (!Number.isFinite(latitude) || latitude < -90 || latitude > 90 || !Number.isFinite(longitude) || longitude < -180 || longitude > 180) throw new Error("Coordenadas inválidas."); const url = new URL("https://rest.isric.org/soilgrids/v2.0/properties/query"); url.searchParams.set("lat", String(latitude)); url.searchParams.set("lon", String(longitude)); properties.forEach((property) => url.searchParams.append("property", property)); depths.forEach((depth) => url.searchParams.append("depth", depth)); ["mean", "Q0.05", "Q0.95"].forEach((value) => url.searchParams.append("value", value)); const response = await fetch(url, { signal }); if (!response.ok) throw new Error(`SoilGrids indisponível (${response.status}). A API REST beta pode estar temporariamente pausada.`); const estimates = parseSoilGridsResponse(await response.json() as ApiResponse); if (!estimates.length) throw new Error("O SoilGrids não devolveu estimativas para este ponto."); return { latitude, longitude, queriedAt: new Date().toISOString(), source: "SoilGrids / ISRIC", resolutionMeters: 250, estimates }; }
