import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Download, FileArchive, FilePlus2, ShieldAlert, Trash2 } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { deleteComplianceDocument, downloadComplianceDocument, listComplianceDocuments, saveComplianceDocument } from "../services/complianceDocumentStorage";
import { readComplianceProfile } from "../services/complianceStorage";
import type { ComplianceDocument } from "../types/compliance";
import { checksumFile, documentValidity, summarizeDocumentValidity, validateComplianceFile, type DocumentValidity } from "../utils/complianceDocuments";
import { EMPTY_COMPLIANCE_PROFILE, evaluateComplianceProfile } from "../utils/complianceProfile";

const inputClass = "h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";
const categoryLabels = { licence: "Licença ou título", certificate: "Certificado", proof: "Comprovativo", invoice: "Fatura", other: "Outro" } as const;
const validityUi: Record<DocumentValidity, { label: string; className: string }> = {
  valid: { label: "Válido", className: "bg-emerald-50 text-emerald-800" }, expiring: { label: "A expirar", className: "bg-amber-50 text-amber-900" }, expired: { label: "Expirado", className: "bg-red-50 text-red-800" }, no_expiry: { label: "Sem validade indicada", className: "bg-slate-100 text-slate-700" },
};

export default function ComplianceDocumentsPage() {
  const obligations = useMemo(() => evaluateComplianceProfile(readComplianceProfile() ?? EMPTY_COMPLIANCE_PROFILE), []);
  const [documents, setDocuments] = useState<ComplianceDocument[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const [title, setTitle] = useState(""); const [obligationId, setObligationId] = useState(obligations[0]?.id ?? ""); const [category, setCategory] = useState<ComplianceDocument["category"]>("licence"); const [issuer, setIssuer] = useState(""); const [reference, setReference] = useState(""); const [issuedAt, setIssuedAt] = useState(""); const [expiresAt, setExpiresAt] = useState(""); const [file, setFile] = useState<File | null>(null);
  const today = new Date().toISOString().slice(0, 10); const summary = useMemo(() => summarizeDocumentValidity(documents, today), [documents, today]);
  useEffect(() => { listComplianceDocuments().then((items) => setDocuments(items.sort((a, b) => b.addedAt.localeCompare(a.addedAt)))).catch((cause) => setError(cause instanceof Error ? cause.message : "Não foi possível consultar os documentos.")); }, []);
  async function addDocument() { setError(""); setMessage(""); if (!title.trim() || !obligationId || !file) { setError("Preencha o título, escolha a obrigação e selecione um ficheiro."); return; } const fileError = validateComplianceFile(file); if (fileError) { setError(fileError); return; } setSaving(true); try { const id = `DOC-${Date.now().toString(36).toUpperCase()}`; const metadata: ComplianceDocument = { id, obligationId, title: title.trim(), category, issuer: issuer.trim(), reference: reference.trim(), issuedAt, expiresAt, fileName: file.name, mimeType: file.type, size: file.size, checksum: await checksumFile(file), addedAt: new Date().toISOString() }; await saveComplianceDocument({ ...metadata, file }); setDocuments((current) => [metadata, ...current]); setTitle(""); setIssuer(""); setReference(""); setIssuedAt(""); setExpiresAt(""); setFile(null); const input = window.document.getElementById("compliance-file") as HTMLInputElement | null; if (input) input.value = ""; setMessage("Documento guardado apenas neste dispositivo."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível guardar o documento."); } finally { setSaving(false); } }
  async function removeDocument(document: ComplianceDocument) { if (!window.confirm(`Eliminar “${document.title}” deste dispositivo?`)) return; try { await deleteComplianceDocument(document.id); setDocuments((current) => current.filter((item) => item.id !== document.id)); setMessage("Documento eliminado do armazenamento local."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível eliminar o documento."); } }

  return <div className="mx-auto max-w-[1400px] space-y-6"><header><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 76 · Documentos de conformidade</p><h1 className="mt-1 text-3xl font-black">Cofre Documental</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Licenças, certificados e comprovativos associados às obrigações da exploração.</p></header>
    <Card className="border-red-200 bg-red-50 p-5"><p className="flex items-start gap-3 text-sm text-red-950"><ShieldAlert className="shrink-0"/><span><b>Armazenamento local, não cifrado.</b> Os anexos ficam no IndexedDB deste navegador, não são enviados para servidores e não entram no backup JSON da Sprint 70. Não use um computador partilhado. Mantenha cópias externas protegidas.</span></p></Card>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Documentos</p><p className="mt-2 text-3xl font-black">{documents.length}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Válidos</p><p className="mt-2 text-3xl font-black text-emerald-700">{summary.valid}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">A expirar em 30 dias</p><p className="mt-2 text-3xl font-black text-amber-700">{summary.expiring}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Expirados</p><p className="mt-2 text-3xl font-black text-red-700">{summary.expired}</p></Card></section>
    <Card className="p-5"><h2 className="flex items-center gap-2 text-xl font-black"><FilePlus2 className="text-emerald-700"/> Adicionar documento</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="grid gap-1 text-sm font-semibold">Título<input className={inputClass} maxLength={120} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: Título de captação"/></label><label className="grid gap-1 text-sm font-semibold">Obrigação<select className={inputClass} value={obligationId} onChange={(event) => setObligationId(event.target.value)}>{obligations.map((item) => <option key={item.id} value={item.id}>{item.area} — {item.title}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Categoria<select className={inputClass} value={category} onChange={(event) => setCategory(event.target.value as ComplianceDocument["category"])}>{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Entidade emissora<input className={inputClass} maxLength={100} value={issuer} onChange={(event) => setIssuer(event.target.value)} placeholder="Ex.: APA"/></label><label className="grid gap-1 text-sm font-semibold">Referência<input className={inputClass} maxLength={100} value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Número opcional"/></label><label className="grid gap-1 text-sm font-semibold">Data de emissão<input type="date" className={inputClass} value={issuedAt} onChange={(event) => setIssuedAt(event.target.value)}/></label><label className="grid gap-1 text-sm font-semibold">Data de validade<input type="date" className={inputClass} value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)}/></label><label className="grid gap-1 text-sm font-semibold">Anexo até 5 MB<input id="compliance-file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="block h-11 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs" onChange={(event) => setFile(event.target.files?.[0] ?? null)}/></label></div><div className="mt-5 flex flex-wrap items-center gap-3"><Button onClick={() => void addDocument()} loading={saving}><FileArchive size={18}/> Guardar documento</Button><p className="text-xs text-slate-500">PDF, JPEG, PNG ou WebP. É calculado SHA-256 para verificar a identidade do ficheiro.</p></div>{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</p>}{message && <p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</p>}</Card>
    <Card className="overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-black">Documentos guardados</h2></div>{documents.length === 0 ? <div className="p-10 text-center"><FileArchive className="mx-auto text-slate-300" size={48}/><p className="mt-3 font-black">Nenhum documento neste navegador</p></div> : <div className="divide-y divide-slate-100">{documents.map((document) => { const validity = documentValidity(document, today); const ui = validityUi[validity]; const obligation = obligations.find((item) => item.id === document.obligationId); return <article key={document.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_220px_170px]"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{document.title}</h3><span className={`rounded-full px-3 py-1 text-xs font-black ${ui.className}`}>{ui.label}</span></div><p className="mt-1 text-sm text-slate-600">{categoryLabels[document.category]} · {document.issuer || "Entidade não indicada"} {document.reference && `· ${document.reference}`}</p><p className="mt-2 text-xs text-slate-500">{obligation?.title ?? document.obligationId} · {(document.size / 1024).toFixed(1)} KiB · SHA-256 {document.checksum.slice(0, 12)}…</p></div><div className="text-sm"><p><b>Emissão:</b> {document.issuedAt || "Não indicada"}</p><p className="mt-1"><b>Validade:</b> {document.expiresAt || "Não indicada"}</p><p className="mt-1 text-xs text-slate-500">Adicionado em {new Date(document.addedAt).toLocaleString("pt-PT")}</p></div><div className="flex items-center justify-end gap-2"><Button size="icon" variant="secondary" aria-label={`Descarregar ${document.title}`} onClick={() => void downloadComplianceDocument(document.id).catch((cause) => setError(cause instanceof Error ? cause.message : "Falha no download."))}><Download size={17}/></Button><Button size="icon" variant="danger" aria-label={`Eliminar ${document.title}`} onClick={() => void removeDocument(document)}><Trash2 size={17}/></Button></div></article>; })}</div>}</Card>
    <p className="flex items-start gap-2 text-xs text-slate-500"><AlertTriangle size={15} className="shrink-0"/> O aviso de validade usa a data indicada pelo utilizador. Confirme sempre o documento e as regras da entidade emissora.</p></div>;
}
