import { useState, type FormEvent } from "react";
import { Download, Gauge, Plus, Trash2, Wrench } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { completeMachineMaintenance, createMachine, deleteMachine, listMachines, registerMachineUsage } from "../services/machineryStorage";
import type { MachineCategory, MachineDraft, MachineStatus } from "../types/machinery";
import { downloadMachineryCsv, getMaintenanceState, machineCategoryLabels, summarizeMachinery } from "../utils/machinery";

const today = new Date().toISOString().slice(0, 10);
const emptyDraft: MachineDraft = { name: "", category: "tractor", brand: "", model: "", registration: "", status: "active", currentHours: 0, fuelConsumedLiters: 0, hourlyCost: 0, lastMaintenanceDate: "", nextMaintenanceDate: "", nextMaintenanceHours: null, notes: "" };
const inputClass = "mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";

export default function MachineryPage() {
  const [machines, setMachines] = useState(() => listMachines()); const [draft, setDraft] = useState(emptyDraft); const [error, setError] = useState("");
  const summary = summarizeMachinery(machines, today);
  function submit(event: FormEvent) { event.preventDefault(); if (!draft.name.trim() || draft.currentHours < 0 || draft.fuelConsumedLiters < 0 || draft.hourlyCost < 0) { setError("Preencha o nome e utilize valores válidos."); return; } const created = createMachine(draft); setMachines((current) => [created, ...current]); setDraft(emptyDraft); setError(""); }
  function usage(id: string) { const hours = window.prompt("Horas de utilização a adicionar:"); if (hours === null) return; const fuel = window.prompt("Combustível consumido em litros:", "0"); if (fuel === null) return; try { setMachines(registerMachineUsage(id, Number(hours.replace(",", ".")), Number(fuel.replace(",", ".")))); } catch (usageError) { window.alert(usageError instanceof Error ? usageError.message : "Utilização inválida."); } }
  function maintenance(id: string) { const nextDate = window.prompt("Data da próxima manutenção (AAAA-MM-DD):", ""); if (nextDate === null) return; const nextHoursRaw = window.prompt("Horas para a próxima manutenção (vazio se não aplicável):", ""); if (nextHoursRaw === null) return; const nextHours = nextHoursRaw.trim() ? Number(nextHoursRaw.replace(",", ".")) : null; setMachines(completeMachineMaintenance(id, today, nextDate, nextHours)); }
  function remove(id: string) { if (window.confirm("Apagar esta máquina?")) setMachines(deleteMachine(id)); }

  return <div className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 62 · Ativos agrícolas</p><h1 className="mt-1 text-3xl font-black">Gestão de máquinas</h1><p className="mt-2 text-sm text-slate-600">Máquinas e utilizações registadas pelo utilizador, guardadas localmente neste navegador.</p></div><Button variant="secondary" onClick={() => downloadMachineryCsv(machines, today, new Date().toISOString())}><Download size={18}/> Exportar máquinas CSV</Button></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Máquinas</p><p className="mt-2 text-3xl font-black">{summary.machines}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Ativas</p><p className="mt-2 text-3xl font-black text-green-700">{summary.active}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Alertas de manutenção</p><p className="mt-2 text-3xl font-black text-amber-700">{summary.maintenanceAlerts}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Combustível acumulado</p><p className="mt-2 text-3xl font-black">{summary.totalFuel} l</p><p className="text-xs text-slate-500">Custo estimado: {summary.estimatedUsageCost.toFixed(2)} €</p></Card></section>
    <Card className="p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-black"><Plus className="text-emerald-700"/> Nova máquina</h2><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm font-semibold sm:col-span-2">Nome *<input className={inputClass} value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })}/></label><label className="text-sm font-semibold">Categoria<select className={inputClass} value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value as MachineCategory })}>{Object.entries(machineCategoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold">Estado<select className={inputClass} value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as MachineStatus })}><option value="active">Ativa</option><option value="maintenance">Em manutenção</option><option value="inactive">Inativa</option></select></label>
      <label className="text-sm font-semibold">Marca<input className={inputClass} value={draft.brand} onChange={(e) => setDraft({ ...draft, brand: e.target.value })}/></label><label className="text-sm font-semibold">Modelo<input className={inputClass} value={draft.model} onChange={(e) => setDraft({ ...draft, model: e.target.value })}/></label><label className="text-sm font-semibold">Matrícula/Identificação<input className={inputClass} value={draft.registration} onChange={(e) => setDraft({ ...draft, registration: e.target.value })}/></label><label className="text-sm font-semibold">Horas atuais<input type="number" min="0" step="0.1" className={inputClass} value={draft.currentHours} onChange={(e) => setDraft({ ...draft, currentHours: Number(e.target.value) })}/></label>
      <label className="text-sm font-semibold">Combustível acumulado (l)<input type="number" min="0" step="0.1" className={inputClass} value={draft.fuelConsumedLiters} onChange={(e) => setDraft({ ...draft, fuelConsumedLiters: Number(e.target.value) })}/></label><label className="text-sm font-semibold">Custo por hora (€)<input type="number" min="0" step="0.01" className={inputClass} value={draft.hourlyCost} onChange={(e) => setDraft({ ...draft, hourlyCost: Number(e.target.value) })}/></label><label className="text-sm font-semibold">Última manutenção<input type="date" className={inputClass} value={draft.lastMaintenanceDate} onChange={(e) => setDraft({ ...draft, lastMaintenanceDate: e.target.value })}/></label><label className="text-sm font-semibold">Próxima manutenção<input type="date" className={inputClass} value={draft.nextMaintenanceDate} onChange={(e) => setDraft({ ...draft, nextMaintenanceDate: e.target.value })}/></label>
      <label className="text-sm font-semibold">Próxima manutenção (horas)<input type="number" min="0" step="0.1" className={inputClass} value={draft.nextMaintenanceHours ?? ""} onChange={(e) => setDraft({ ...draft, nextMaintenanceHours: e.target.value ? Number(e.target.value) : null })}/></label><label className="text-sm font-semibold lg:col-span-3">Observações<input className={inputClass} value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })}/></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 sm:col-span-2 lg:col-span-4">{error}</p>}<div className="sm:col-span-2 lg:col-span-4"><Button type="submit"><Gauge size={18}/> Cadastrar máquina</Button></div>
    </form></Card>
    <Card className="overflow-hidden">{machines.length === 0 ? <p className="p-10 text-center text-slate-500">Nenhuma máquina registada.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Máquina", "Estado", "Horas", "Combustível", "Próxima manutenção", "Alerta", "Ações", ""].map((label) => <th key={label} className="px-5 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{machines.map((machine) => { const state = getMaintenanceState(machine, today); return <tr key={machine.id}><td className="px-5 py-4"><b>{machine.name}</b><p className="text-sm text-slate-500">{machineCategoryLabels[machine.category]} · {machine.brand} {machine.model}</p></td><td className="px-5 py-4">{machine.status === "active" ? "Ativa" : machine.status === "maintenance" ? "Em manutenção" : "Inativa"}</td><td className="px-5 py-4 font-black">{machine.currentHours} h</td><td className="px-5 py-4">{machine.fuelConsumedLiters} l</td><td className="px-5 py-4"><p>{machine.nextMaintenanceDate || "Sem data"}</p><p className="text-sm text-slate-500">{machine.nextMaintenanceHours !== null ? `${machine.nextMaintenanceHours} h` : "Sem limite de horas"}</p></td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${state === "overdue" ? "bg-red-100 text-red-700" : state === "due_soon" ? "bg-amber-100 text-amber-700" : "bg-green-100 text-green-700"}`}>{state === "overdue" ? "Vencida" : state === "due_soon" ? "Próxima" : "Em dia"}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={() => usage(machine.id)} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">+ Utilização</button><button onClick={() => maintenance(machine.id)} className="rounded-lg bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700"><Wrench size={14} className="mr-1 inline"/>Manutenção</button></div></td><td className="px-5 py-4"><button onClick={() => remove(machine.id)} aria-label={`Apagar ${machine.name}`} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></td></tr>; })}</tbody></table></div>}</Card>
  </div>;
}
