import type { HarvestQuality, HarvestRecord } from "../types/harvest";

export const harvestQualityLabels: Record<HarvestQuality, string> = { premium: "Premium", first: "Primeira", second: "Segunda", industrial: "Industrial", unclassified: "Não classificada" };
export const quantityInKg = (record: Pick<HarvestRecord, "grossQuantity" | "unit">) => record.unit === "t" ? record.grossQuantity * 1000 : record.grossQuantity;
export const marketableInKg = (record: Pick<HarvestRecord, "marketableQuantity" | "unit">) => record.unit === "t" ? record.marketableQuantity * 1000 : record.marketableQuantity;
export function calculateHarvestMetrics(record: HarvestRecord) {
  const grossKg = quantityInKg(record); const marketableKg = Math.min(grossKg, marketableInKg(record)); const lossKg = Math.max(0, grossKg - marketableKg);
  return { grossKg: Number(grossKg.toFixed(2)), marketableKg: Number(marketableKg.toFixed(2)), lossKg: Number(lossKg.toFixed(2)), lossPercent: grossKg ? Number(((lossKg / grossKg) * 100).toFixed(2)) : 0, yieldTonsPerHa: record.harvestedAreaHa > 0 ? Number(((grossKg / 1000) / record.harvestedAreaHa).toFixed(2)) : 0 };
}
export function summarizeHarvest(records: HarvestRecord[]) { const totals = records.reduce((acc, record) => { const metrics = calculateHarvestMetrics(record); acc.grossKg += metrics.grossKg; acc.marketableKg += metrics.marketableKg; acc.lossKg += metrics.lossKg; acc.areaHa += Math.max(0, record.harvestedAreaHa); return acc; }, { grossKg: 0, marketableKg: 0, lossKg: 0, areaHa: 0 }); return { records: records.length, grossTons: Number((totals.grossKg / 1000).toFixed(2)), marketableTons: Number((totals.marketableKg / 1000).toFixed(2)), lossTons: Number((totals.lossKg / 1000).toFixed(2)), lossPercent: totals.grossKg ? Number(((totals.lossKg / totals.grossKg) * 100).toFixed(2)) : 0, yieldTonsPerHa: totals.areaHa ? Number(((totals.grossKg / 1000) / totals.areaHa).toFixed(2)) : 0 }; }
const escapeCsv = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`;
export function buildHarvestCsv(records: HarvestRecord[], generatedAt: string) { const rows = records.map((record) => { const metrics = calculateHarvestMetrics(record); return [record.id, record.campaign, record.harvestDate, record.farm, record.field, record.crop, record.harvestedAreaHa, record.grossQuantity, record.marketableQuantity, record.unit, metrics.lossKg, metrics.lossPercent, metrics.yieldTonsPerHa, harvestQualityLabels[record.quality], record.destination, record.notes, generatedAt]; }); return [["ID", "Campanha", "Data", "Exploração", "Talhão", "Cultura", "Área colhida (ha)", "Produção bruta", "Produção comercializável", "Unidade", "Perdas (kg)", "Perdas (%)", "Produtividade (t/ha)", "Qualidade", "Destino", "Observações", "Exportado em"], ...rows].map((row) => row.map(escapeCsv).join(";")).join("\r\n"); }
export function downloadHarvestCsv(records: HarvestRecord[], generatedAt: string) { const blob = new Blob([`\uFEFF${buildHarvestCsv(records, generatedAt)}`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "farpha-producao-colheita.csv"; anchor.click(); URL.revokeObjectURL(url); }
