export type FarphaRole = "owner" | "manager" | "operator" | "viewer";
export type Permission = "manage_users" | "manage_farms" | "edit_operations" | "view_reports" | "export_data" | "restore_backup";
export const roleLabels: Record<FarphaRole, string> = { owner: "Proprietário", manager: "Gestor", operator: "Operador", viewer: "Consulta" };
const permissions: Record<FarphaRole, Permission[]> = { owner: ["manage_users", "manage_farms", "edit_operations", "view_reports", "export_data", "restore_backup"], manager: ["manage_farms", "edit_operations", "view_reports", "export_data", "restore_backup"], operator: ["edit_operations", "view_reports"], viewer: ["view_reports"] };
export function roleCan(role: FarphaRole, permission: Permission) { return permissions[role].includes(permission); }

export type ProductionCheck = { id: string; label: string; status: "ready" | "warning" | "blocked"; detail: string };
export function buildProductionChecks(input: { supabaseUrl: string; anonKey: string; protocol: string; serviceWorker: boolean; storage: boolean; authConfigured: boolean; rlsConfirmed: boolean; backupPolicyConfirmed: boolean }): ProductionCheck[] { const validUrl = /^https:\/\/.+\.supabase\.co$/i.test(input.supabaseUrl); const validKey = input.anonKey.length > 40 && !input.anonKey.includes("YOUR_"); return [
  { id: "supabase", label: "Configuração Supabase", status: validUrl && validKey ? "ready" : "blocked", detail: validUrl && validKey ? "URL e chave pública configuradas." : "Configure VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY." },
  { id: "https", label: "HTTPS", status: input.protocol === "https:" || input.protocol === "http://localhost" ? "ready" : "blocked", detail: "Produção e PWA devem ser servidas através de HTTPS." },
  { id: "pwa", label: "Service worker", status: input.serviceWorker ? "ready" : "warning", detail: input.serviceWorker ? "Navegador compatível com modo offline." : "Service worker indisponível neste navegador." },
  { id: "storage", label: "Armazenamento local", status: input.storage ? "ready" : "blocked", detail: input.storage ? "Backup local disponível." : "localStorage indisponível ou bloqueado." },
  { id: "auth", label: "Autenticação", status: input.authConfigured ? "ready" : "blocked", detail: input.authConfigured ? "Fluxo de autenticação confirmado." : "Autenticação ainda não confirmada para produção." },
  { id: "rls", label: "Row Level Security", status: input.rlsConfirmed ? "ready" : "blocked", detail: input.rlsConfirmed ? "Políticas RLS confirmadas." : "Confirme RLS em todas as tabelas no Supabase." },
  { id: "remote-backup", label: "Backup remoto", status: input.backupPolicyConfirmed ? "ready" : "blocked", detail: input.backupPolicyConfirmed ? "Política de backup remoto confirmada." : "Defina retenção e teste de recuperação do Supabase." },
]; }

export type LocalBackup = { format: "farpha-local-backup"; version: 1; createdAt: string; entries: Record<string, string> };
export function createLocalBackup(storage: Pick<Storage, "length" | "key" | "getItem">, createdAt: string): LocalBackup { const entries: Record<string, string> = {}; for (let index = 0; index < storage.length; index += 1) { const key = storage.key(index); if (key?.startsWith("farpha.")) { const value = storage.getItem(key); if (value !== null) entries[key] = value; } } return { format: "farpha-local-backup", version: 1, createdAt, entries }; }
export function parseLocalBackup(text: string): LocalBackup { const value: unknown = JSON.parse(text); if (!value || typeof value !== "object" || !("format" in value) || value.format !== "farpha-local-backup" || !("version" in value) || value.version !== 1 || !("entries" in value) || !value.entries || typeof value.entries !== "object" || Array.isArray(value.entries)) throw new Error("Ficheiro de backup FARPHA inválido ou incompatível."); const entries = value.entries as Record<string, unknown>; if (Object.entries(entries).some(([key, item]) => !key.startsWith("farpha.") || typeof item !== "string")) throw new Error("O backup contém entradas não permitidas."); return value as LocalBackup; }
export function restoreLocalBackup(backup: LocalBackup, storage: Pick<Storage, "setItem">) { Object.entries(backup.entries).forEach(([key, value]) => storage.setItem(key, value)); return Object.keys(backup.entries).length; }
export function downloadLocalBackup(backup: LocalBackup) { const blob = new Blob([JSON.stringify(backup, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `farpha-backup-local-${backup.createdAt.slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); }
