import type { FieldDiaryEntry } from "../../field-diary/types/fieldDiary";
import { diaryActivityLabels } from "../../field-diary/utils/fieldDiary";
import type { HarvestRecord } from "../../harvest/types/harvest";
import { calculateHarvestMetrics, harvestQualityLabels } from "../../harvest/utils/harvest";
import type{AgriculturalTreatment}from"../../treatments/types/treatment";

export type TraceabilityStage = "soil" | "planting" | "care" | "irrigation" | "harvest" | "observation";
export type TraceabilityEvent = { id: string; date: string; farm: string; field: string; crop: string; stage: TraceabilityStage; activity: string; title: string; responsible: string; details: string; source: "Diário local" | "Colheitas locais" | "Tratamentos locais"; lotCode?:string; evidenceReference?:string };
export type TraceabilityFilters = { farm: string; field: string; crop: string; startDate: string; endDate: string };

const stageByActivity: Record<FieldDiaryEntry["activity"], TraceabilityStage> = { soil_preparation: "soil", planting: "planting", irrigation: "irrigation", fertilization: "care", spraying: "care", pruning: "care", harvest: "harvest", inspection: "observation", maintenance: "care", observation: "observation", other: "observation" };
export const traceabilityStageLabels: Record<TraceabilityStage, string> = { soil: "Preparação do solo", planting: "Plantação", care: "Cuidados culturais", irrigation: "Rega", harvest: "Colheita", observation: "Inspeção e observação" };

export function buildTraceabilityEvents(diary: FieldDiaryEntry[], harvests: HarvestRecord[],treatments:AgriculturalTreatment[]=[] ) {
  const events: TraceabilityEvent[] = diary.map((entry) => ({ id: `diary-${entry.id}`, date: entry.date, farm: entry.farm, field: entry.field, crop: entry.crop, stage: stageByActivity[entry.activity], activity: diaryActivityLabels[entry.activity], title: entry.title, responsible: entry.responsible, details: [entry.product,entry.quantity&&entry.unit?`${entry.quantity} ${entry.unit}`:"",entry.equipment,entry.weather, entry.notes, entry.photoName ? `Fotografia: ${entry.photoName}` : ""].filter(Boolean).join(" · "), source: "Diário local" as const,evidenceReference:entry.evidenceReference }));
  treatments.forEach(v=>events.push({id:`treatment-${v.id}`,date:v.date,farm:v.farm,field:v.field,crop:v.crop,stage:"care",activity:v.kind==="plant_protection"?"Tratamento fitofarmacêutico":"Fertilização",title:v.productName,responsible:v.applicator,details:`${v.totalQuantity} ${v.doseUnit} · ${v.equipment}${v.authorizationNumber?` · APV ${v.authorizationNumber}`:""}${v.harvestAllowedFrom?` · Colheita permitida desde ${v.harvestAllowedFrom}`:""}`,source:"Tratamentos locais"}));
  harvests.forEach((record) => { const metrics = calculateHarvestMetrics(record); events.push({ id: `harvest-${record.id}`, date: record.harvestDate, farm: record.farm, field: record.field, crop: record.crop, stage: "harvest", activity: "Colheita registada", title: `${record.grossQuantity} ${record.unit} · ${harvestQualityLabels[record.quality]}`, responsible: record.releasedBy||"Não informado no registo de colheita", details: `Campanha ${record.campaign} · Lote ${record.lotCode||"por indicar"} · Perdas ${metrics.lossPercent}% · Produtividade ${metrics.yieldTonsPerHa} t/ha${record.destination ? ` · Destino: ${record.destination}` : ""} · Segurança ${record.safetyStatus||"pendente"}`, source: "Colheitas locais",lotCode:record.lotCode,evidenceReference:record.safetyEvidenceReference }); });
  return events.sort((a, b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id));
}

const same=(a:string,b:string)=>a.trim().toLocaleLowerCase("pt-PT")===b.trim().toLocaleLowerCase("pt-PT");
export function assessLotTraceability(harvest:HarvestRecord,events:TraceabilityEvent[]){const related=events.filter(v=>v.date<=harvest.harvestDate&&same(v.farm,harvest.farm)&&same(v.field,harvest.field)&&(!v.crop||!harvest.crop||same(v.crop,harvest.crop)));const checks={lot:Boolean(harvest.lotCode?.trim()),fieldHistory:related.some(v=>v.source==="Diário local"),treatments:related.some(v=>v.source==="Tratamentos locais"),harvest:true,safety:harvest.safetyStatus==="released"&&Boolean(harvest.releasedBy?.trim())&&Boolean(harvest.safetyEvidenceReference?.trim())&&!harvest.contaminationIncident,destination:Boolean(harvest.destination.trim())};const complete=Object.values(checks).filter(Boolean).length;return{checks,complete,total:Object.keys(checks).length,percent:Math.round(complete/Object.keys(checks).length*100),relatedEvents:related.length}}
export function summarizeLotTraceability(harvests:HarvestRecord[],events:TraceabilityEvent[]){const assessments=harvests.map(v=>assessLotTraceability(v,events));return{lots:harvests.length,complete:assessments.filter(v=>v.percent===100).length,attention:assessments.filter(v=>v.percent<100).length,averagePercent:assessments.length?Math.round(assessments.reduce((a,v)=>a+v.percent,0)/assessments.length):0}}

export function filterTraceabilityEvents(events: TraceabilityEvent[], filters: TraceabilityFilters) { const farm = filters.farm.trim().toLowerCase(); const field = filters.field.trim().toLowerCase(); const crop = filters.crop.trim().toLowerCase(); return events.filter((event) => (!farm || event.farm.toLowerCase().includes(farm)) && (!field || event.field.toLowerCase().includes(field)) && (!crop || event.crop.toLowerCase().includes(crop)) && (!filters.startDate || event.date >= filters.startDate) && (!filters.endDate || event.date <= filters.endDate)); }
export function summarizeTraceability(events: TraceabilityEvent[]) { const required: TraceabilityStage[] = ["soil", "planting", "care", "irrigation", "harvest"]; const present = new Set(events.map((event) => event.stage)); const completedStages = required.filter((stage) => present.has(stage)); return { events: events.length, completedStages, missingStages: required.filter((stage) => !present.has(stage)), coveragePercent: Math.round((completedStages.length / required.length) * 100), firstDate: events[0]?.date ?? null, lastDate: events.at(-1)?.date ?? null }; }
const escapeCsv = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`;
export function buildTraceabilityCsv(events: TraceabilityEvent[], generatedAt: string) { const summary = summarizeTraceability(events); const rows: Array<Array<string | number>> = [["Resumo", "Cobertura das etapas (%)", summary.coveragePercent, summary.missingStages.map((stage) => traceabilityStageLabels[stage]).join(", ") || "Todas as etapas possuem evidência"]]; events.forEach((event) => rows.push([event.date, `${event.farm} / ${event.field} / ${event.crop || "Cultura não definida"}`, `${traceabilityStageLabels[event.stage]} · ${event.activity} · ${event.title}`, `${event.responsible} · ${event.details} · Origem: ${event.source}`])); rows.push(["Relatório", "Gerado em", generatedAt, "Fontes locais identificadas"]); return [["Data/Secção", "Local/Indicador", "Etapa/Evento", "Responsável/Detalhes/Origem"], ...rows].map((row) => row.map(escapeCsv).join(";")).join("\r\n"); }
export function downloadTraceabilityCsv(events: TraceabilityEvent[], generatedAt: string) { const blob = new Blob([`\uFEFF${buildTraceabilityCsv(events, generatedAt)}`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "farpha-rastreabilidade.csv"; anchor.click(); URL.revokeObjectURL(url); }
