import { useMemo, useState } from "react";
import { CheckCircle2, Download, ShieldCheck } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { listFieldDiaryEntries } from "../../field-diary/services/fieldDiaryStorage";
import { listHarvestRecords } from "../../harvest/services/harvestStorage";
import { buildTraceabilityEvents, downloadTraceabilityCsv, filterTraceabilityEvents, summarizeTraceability, traceabilityStageLabels, type TraceabilityFilters } from "../utils/traceability";

const initialFilters: TraceabilityFilters = { farm: "", field: "", crop: "", startDate: "", endDate: "" };
const inputClass = "h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";

export default function TraceabilityPage() {
  const [diary] = useState(() => listFieldDiaryEntries()); const [harvests] = useState(() => listHarvestRecords()); const [filters, setFilters] = useState(initialFilters);
  const allEvents = useMemo(() => buildTraceabilityEvents(diary, harvests), [diary, harvests]); const events = useMemo(() => filterTraceabilityEvents(allEvents, filters), [allEvents, filters]); const summary = summarizeTraceability(events);
  return <div className="mx-auto max-w-[1400px] space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 65 · Cadeia de evidências</p><h1 className="mt-1 text-3xl font-black">Rastreabilidade agrícola</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Linha temporal formada exclusivamente pelos registos locais do Diário do Talhão e de Produção/Colheita.</p></div><Button onClick={() => downloadTraceabilityCsv(events, new Date().toISOString())}><Download size={18}/> Exportar rastreabilidade CSV</Button></header>
    <Card className="p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><input className={inputClass} placeholder="Exploração" value={filters.farm} onChange={(e) => setFilters({ ...filters, farm: e.target.value })}/><input className={inputClass} placeholder="Talhão" value={filters.field} onChange={(e) => setFilters({ ...filters, field: e.target.value })}/><input className={inputClass} placeholder="Cultura" value={filters.crop} onChange={(e) => setFilters({ ...filters, crop: e.target.value })}/><input type="date" className={inputClass} value={filters.startDate} onChange={(e) => setFilters({ ...filters, startDate: e.target.value })}/><input type="date" className={inputClass} value={filters.endDate} onChange={(e) => setFilters({ ...filters, endDate: e.target.value })}/></div><button type="button" onClick={() => setFilters(initialFilters)} className="mt-4 text-sm font-bold text-emerald-700">Limpar filtros</button></Card>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Evidências</p><p className="mt-2 text-3xl font-black">{summary.events}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Cobertura das etapas</p><p className="mt-2 text-3xl font-black">{summary.coveragePercent}%</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Primeiro registo</p><p className="mt-2 text-xl font-black">{summary.firstDate ? new Date(`${summary.firstDate}T12:00:00`).toLocaleDateString("pt-PT") : "Sem dados"}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Último registo</p><p className="mt-2 text-xl font-black">{summary.lastDate ? new Date(`${summary.lastDate}T12:00:00`).toLocaleDateString("pt-PT") : "Sem dados"}</p></Card></section>
    <Card className="p-5"><h2 className="flex items-center gap-2 text-xl font-black"><ShieldCheck className="text-emerald-700"/> Cobertura do ciclo</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{(["soil", "planting", "care", "irrigation", "harvest"] as const).map((stage) => { const present = summary.completedStages.includes(stage); return <div key={stage} className={`rounded-xl border p-4 ${present ? "border-green-200 bg-green-50" : "border-amber-200 bg-amber-50"}`}><p className="flex items-center gap-2 font-bold">{present && <CheckCircle2 size={17} className="text-green-700"/>}{traceabilityStageLabels[stage]}</p><p className="mt-1 text-xs text-slate-600">{present ? "Possui evidência" : "Sem evidência registada"}</p></div>; })}</div><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-500">A cobertura mede presença de registos; não certifica conformidade legal nem qualidade da operação.</p></Card>
    <Card className="overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-black">Linha temporal</h2></div>{events.length === 0 ? <p className="p-10 text-center text-slate-500">Nenhuma evidência encontrada. Registe atividades no Diário do Talhão ou em Produção e Colheita.</p> : <div className="divide-y divide-slate-100">{events.map((event) => <article key={event.id} className="grid gap-3 p-5 md:grid-cols-[130px_180px_1fr]"><div><p className="font-black">{new Date(`${event.date}T12:00:00`).toLocaleDateString("pt-PT")}</p><p className="mt-1 text-xs text-slate-500">{event.source}</p></div><div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">{traceabilityStageLabels[event.stage]}</span></div><div><h3 className="font-black">{event.title}</h3><p className="text-sm font-semibold text-slate-700">{event.farm} · {event.field} · {event.crop || "Cultura não definida"}</p><p className="mt-1 text-sm text-slate-600">{event.activity} · {event.responsible}</p>{event.details && <p className="mt-1 text-sm text-slate-500">{event.details}</p>}</div></article>)}</div>}</Card>
  </div>;
}
