import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CloudSun, Download, Droplets, RefreshCw, Wind } from "lucide-react";
import Button from "../../../design-system/components/Button";
import Card from "../../../design-system/components/Card";
import { getFarms } from "../../farms/services/farmsService";
import type { Farm } from "../../farms/types/farm";
import { fetchWeatherForecast } from "../services/weatherService";
import { readWeatherCache, saveWeatherCache } from "../services/weatherCache";
import type { WeatherForecast } from "../types/weather";
import { buildWeatherAlerts, downloadWeatherCsv, weatherCodeLabel } from "../utils/weatherAlerts";

const inputClass = "h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100";
const severityClass = { critical: "border-red-300 bg-red-50 text-red-800", warning: "border-amber-300 bg-amber-50 text-amber-900", info: "border-blue-200 bg-blue-50 text-blue-800" };

export default function WeatherPage() {
  const cached = readWeatherCache(); const [farms, setFarms] = useState<Farm[]>([]); const [farmId, setFarmId] = useState(cached?.farmId ?? ""); const [latitude, setLatitude] = useState(cached?.forecast.latitude ?? 41.1579); const [longitude, setLongitude] = useState(cached?.forecast.longitude ?? -8.6291); const [forecast, setForecast] = useState<WeatherForecast | null>(cached?.forecast ?? null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; getFarms().then((items) => { if (active) setFarms(items); }).catch(() => undefined); return () => { active = false; }; }, []);
  const selectedFarm = farms.find((farm) => farm.id === farmId); const locationLabel = selectedFarm?.name ?? `Localização ${latitude.toFixed(4)}, ${longitude.toFixed(4)}`; const alerts = useMemo(() => buildWeatherAlerts(forecast?.days ?? []), [forecast]);
  function selectFarm(id: string) { setFarmId(id); const farm = farms.find((item) => item.id === id); if (farm) { setLatitude(Number(farm.latitude)); setLongitude(Number(farm.longitude)); } }
  async function refresh() { setLoading(true); setError(""); try { const result = await fetchWeatherForecast(latitude, longitude); setForecast(result); saveWeatherCache(result, locationLabel, farmId); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível consultar a previsão."); } finally { setLoading(false); } }
  return <div className="mx-auto max-w-[1400px] space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">Sprint 67 · Meteorologia por localização</p><h1 className="mt-1 text-3xl font-black">Previsão meteorológica</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Previsão de sete dias e alertas agrícolas calculados para as coordenadas selecionadas.</p></div>{forecast && <Button variant="secondary" onClick={() => downloadWeatherCsv(forecast.days, locationLabel, forecast.generatedAt)}><Download size={18}/> Exportar previsão CSV</Button>}</header>
    <Card className="p-5"><div className="grid gap-4 md:grid-cols-4"><label className="grid gap-1 text-sm font-semibold">Exploração<select className={inputClass} value={farmId} onChange={(e) => selectFarm(e.target.value)}><option value="">Coordenadas manuais</option>{farms.map((farm) => <option key={farm.id} value={farm.id}>{farm.name}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Latitude<input type="number" step="0.0001" className={inputClass} disabled={Boolean(farmId)} value={latitude} onChange={(e) => setLatitude(Number(e.target.value))}/></label><label className="grid gap-1 text-sm font-semibold">Longitude<input type="number" step="0.0001" className={inputClass} disabled={Boolean(farmId)} value={longitude} onChange={(e) => setLongitude(Number(e.target.value))}/></label><div className="flex items-end"><Button className="w-full" onClick={refresh} disabled={loading}>{loading ? <RefreshCw className="animate-spin" size={18}/> : <CloudSun size={18}/>} {loading ? "A consultar…" : "Atualizar previsão"}</Button></div></div>{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error} Confirme a ligação à Internet e tente novamente.</p>}<p className="mt-4 text-xs text-slate-500">Localização atual: {locationLabel}. As explorações são carregadas do seu projeto; também pode introduzir coordenadas manualmente.</p></Card>
    {!forecast ? <Card className="grid min-h-64 place-items-center p-8 text-center"><div><CloudSun className="mx-auto text-slate-300" size={52}/><h2 className="mt-3 text-xl font-black">Consulte a previsão da localização</h2><p className="mt-2 text-sm text-slate-500">Os dados só aparecem depois de uma consulta real ao serviço meteorológico.</p></div></Card> : <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Dias previstos</p><p className="mt-2 text-3xl font-black">{forecast.days.length}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Alertas agrícolas</p><p className="mt-2 text-3xl font-black">{alerts.length}</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Chuva acumulada</p><p className="mt-2 text-3xl font-black">{forecast.days.reduce((sum, day) => sum + day.precipitationMm, 0).toFixed(1)} mm</p></Card><Card className="p-5"><p className="text-sm font-semibold text-slate-500">Fonte</p><p className="mt-2 text-xl font-black">{forecast.source}</p><p className="text-xs text-slate-500">Fuso: {forecast.timezone}</p></Card></section>
      <Card className="p-5"><h2 className="flex items-center gap-2 text-xl font-black"><AlertTriangle className="text-amber-500"/> Alertas agrícolas</h2>{alerts.length === 0 ? <p className="mt-4 rounded-xl bg-green-50 p-4 text-sm font-semibold text-green-800">Nenhum limiar de alerta foi atingido nesta previsão.</p> : <div className="mt-4 grid gap-3 lg:grid-cols-2">{alerts.map((alert) => <article key={alert.id} className={`rounded-xl border p-4 ${severityClass[alert.severity]}`}><p className="text-xs font-black uppercase">{new Date(`${alert.date}T12:00:00`).toLocaleDateString("pt-PT")} · {alert.severity}</p><h3 className="mt-1 font-black">{alert.title}</h3><p className="mt-1 text-sm">{alert.recommendation}</p></article>)}</div>}</Card>
      <Card className="overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-black">Previsão de sete dias</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Data", "Condição", "Temperatura", "Chuva", "Rajadas", "ET₀"].map((label) => <th key={label} className="px-5 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{forecast.days.map((day) => <tr key={day.date}><td className="px-5 py-4 font-black">{new Date(`${day.date}T12:00:00`).toLocaleDateString("pt-PT", { weekday: "short", day: "2-digit", month: "2-digit" })}</td><td className="px-5 py-4"><span className="flex items-center gap-2"><CloudSun size={18}/>{weatherCodeLabel(day.weatherCode)}</span></td><td className="px-5 py-4"><b>{day.temperatureMin}–{day.temperatureMax} °C</b></td><td className="px-5 py-4"><span className="flex items-center gap-2"><Droplets size={17} className="text-blue-600"/>{day.precipitationMm} mm · {day.precipitationProbability}%</span></td><td className="px-5 py-4"><span className="flex items-center gap-2"><Wind size={17}/>{day.windGustKmh} km/h</span></td><td className="px-5 py-4">{day.evapotranspirationMm} mm</td></tr>)}</tbody></table></div></Card>
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Previsões são estimativas de modelos meteorológicos. Confirme alertas críticos em fontes oficiais e nas condições locais.</p>
    </>}
  </div>;
}
